// STATE TYPES
export const UPDATE_STATE = 'STATE/UPDATE_STATE'
// SOUND TYPES
export const UPDATE_SOUND = 'SOUND/UPDATE_SOUND'
// FRETBOARD TYPES
export const UPDATE_FRETBOARD = 'FRETBOARD/UPDATE_FRETBOARD'
// PLAYER TYPES
export const UPDATE_PLAYER = 'PLAYER/UPDATE_PLAYER'
