export const CHANGE_PATTERN_SIZE = 'SETUP/CHANGE_PATTERN_SIZE'
export const CHANGE_PATTERN_PARTS = 'SETUP/CHANGE_PATTERN_PARTS'
export const CHANGE_INSTRUMENT = 'SETUP/CHANGE_INSTRUMENT'
export const CHANGE_STATE = 'SETUP/CHANGE_STATE'

export const GENERATE_PATTERN = 'LIST/GENERATE_PATTERN'

export const PLAY = 'PLAYER/PLAY'
export const PAUSE = 'PLAYER/PAUSE'
export const REFRESH = 'PLAYER/REFRESH'
export const SHOW_NOTE_ON_PLAY = 'PLAYER/SHOW_NOTE_ON_PLAY'