//! Constant Values for using in generate values, validate, etc...
export const CLASSNAME_COLORS = [
  'primary',
  'secondary',
  'success',
  'danger',
  'warning',
  'info',
  'light',
  'dark',
  'body',
  'white',
  'transparent'
]
export const FILENAME_BLISS = ['not ready', 'not ready', 'not ready']
export const FILENAME_AUDIO = []
export const COLOR_NAMES = ['blue', 'indigo', 'purple', 'pink', 'red', 'orange', 'yellow', 'green', 'teal', 'cyan']
export const COLOR_NAMES_TEXT = ['black', 'red', 'green', 'yellow', 'blue', 'magenta', 'cyan', 'white']
export const COLOR_NAMES_BACKGROUND = [
  'bgBlack',
  'bgRed',
  'bgGreen',
  'bgYellow',
  'bgBlue',
  'bgMagenta',
  'bgCyan',
  'bgWhite'
]
export const COLOR_HEX = [
  '#ff0000',
  '#ff4e00',
  '#db7b00',
  '#ffcc00',
  '#e4ed00',
  '#81d700',
  '#00ffb4',
  '#00ffea',
  '#00baff',
  '#3c00ff',
  '#a800ff',
  '#ff00fd'
]
export const GRADIENT_NAMES = [
  'cristal',
  'teen',
  'mind',
  'morning',
  'vice',
  'pastel',
  'passion',
  'fruit',
  'instagram',
  'atlas',
  'retro',
  'summer',
  'rainbow'
]
// Note Symbols in #
export const NOTE_CHARS = ['A', 'A#', 'B', 'C', 'C#', 'D', 'D#', 'F', 'E', 'E#', 'G', 'G#']
// Music Scale Names
export const SCALE_NAMES = [
  'major',
  'minor',
  'ionian',
  'dorian',
  'phrygian',
  'lydian',
  'mixolydian',
  'aeolian',
  'locrian',
  'majorpentatonic',
  'minorpentatonic',
  'chromatic',
  'harmonicchromatic',
  'blues',
  'doubleharmonic',
  'flamenco',
  'harmonicminor',
  'melodicminor',
  'wholetone'
]
// Guitar tunings
export const GUITAR_TUNINGS = {
  'E Standart': ['E2', 'A2', 'D3', 'G3', 'B4', 'E4'],
  'Drop D': ['D2', 'A2', 'D3', 'G3', 'B4', 'E4'],
  'Drop C': ['C2', 'G2', 'C3', 'F3', 'A4', 'D4'],
  'Drop B': ['B2', 'F#2', 'B3', 'E3', 'G#3', 'C#4']
}
export const GUITAR_TUNING_NAMES = Object.keys(GUITAR_TUNINGS)
// Tone.js Synths
export const TONE_SYNTHS = [
  'AMSynth',
  'FMSynth',
  'DuoSynth',
  'MembraneSynth',
  'MetalSynth',
  'MonoSynth',
  'NoiseSynth',
  'PluckSynth',
  'PolySynth',
  'Synth'
]
export const TONE_INSTRUMENT_NAMES = [
  'AMSynth',
  'FMSynth',
  'DuoSynth',
  'MembraneSynth',
  'MetalSynth',
  'MonoSynth',
  'NoiseSynth',
  'PluckSynth',
  'PolySynth',
  'Synth'
]
export const NOTE_DURATION_CHARS = ['n', 't', 'm', 'n']
// For note interval finding
export const NOTE_INTERVAL_CHARS = ['P1', 'M2', 'M3', 'P4', 'P5', 'M6', 'M7']
export const CLASSNAME_ICONS = [
  'ofaddress-book',
  'ofaddress-book-o',
  'ofaddress-card',
  'ofaddress-card-o',
  'ofadjust',
  'ofamerican-sign-language-interpreting',
  'ofanchor',
  'ofarchive',
  'ofarea-chart',
  'ofarrows',
  'ofarrows-h',
  'ofarrows-v',
  'ofasl-interpreting (alias)',
  'ofassistive-listening-systems',
  'ofasterisk',
  'ofat',
  'ofaudio-description',
  'ofautomobile (alias)',
  'ofbalance-scale',
  'ofban',
  'ofbank (alias)',
  'ofbar-chart',
  'ofbar-chart-o (alias)',
  'ofbarcode',
  'ofbars',
  'ofbath',
  'ofbathtub (alias)',
  'ofbattery (alias)',
  'ofbattery-0 (alias)',
  'ofbattery-1 (alias)',
  'ofbattery-2 (alias)',
  'ofbattery-3 (alias)',
  'ofbattery-4 (alias)',
  'ofbattery-empty',
  'ofbattery-full',
  'ofbattery-half',
  'ofbattery-quarter',
  'ofbattery-three-quarters',
  'ofbed',
  'ofbeer',
  'ofbell',
  'ofbell-o',
  'ofbell-slash',
  'ofbell-slash-o',
  'ofbicycle',
  'ofbinoculars',
  'ofbirthday-cake',
  'ofblind',
  'ofbluetooth',
  'ofbluetooth-b',
  'ofbolt',
  'ofbomb',
  'ofbook',
  'ofbookmark',
  'ofbookmark-o',
  'ofbraille',
  'ofbriefcase',
  'ofbug',
  'ofbuilding',
  'ofbuilding-o',
  'ofbullhorn',
  'ofbullseye',
  'ofbus',
  'ofcab (alias)',
  'ofcalculator',
  'ofcalendar',
  'ofcalendar-check-o',
  'ofcalendar-minus-o',
  'ofcalendar-o',
  'ofcalendar-plus-o',
  'ofcalendar-times-o',
  'ofcamera',
  'ofcamera-retro',
  'ofcar',
  'ofcaret-square-o-down',
  'ofcaret-square-o-left',
  'ofcaret-square-o-right',
  'ofcaret-square-o-up',
  'ofcart-arrow-down',
  'ofcart-plus',
  'ofcc',
  'ofcertificate',
  'ofcheck',
  'ofcheck-circle',
  'ofcheck-circle-o',
  'ofcheck-square',
  'ofcheck-square-o',
  'ofchild',
  'ofcircle',
  'ofcircle-o',
  'ofcircle-o-notch',
  'ofcircle-thin',
  'ofclock-o',
  'ofclone',
  'ofclose (alias)',
  'ofcloud',
  'ofcloud-download',
  'ofcloud-upload',
  'ofcode',
  'ofcode-fork',
  'ofcoffee',
  'ofcog',
  'ofcogs',
  'ofcomment',
  'ofcomment-o',
  'ofcommenting',
  'ofcommenting-o',
  'ofcomments',
  'ofcomments-o',
  'ofcompass',
  'ofcopyright',
  'ofcreative-commons',
  'ofcredit-card',
  'ofcredit-card-alt',
  'ofcrop',
  'ofcrosshairs',
  'ofcube',
  'ofcubes',
  'ofcutlery',
  'ofdashboard (alias)',
  'ofdatabase',
  'ofdeaf',
  'ofdeafness (alias)',
  'ofdesktop',
  'ofdiamond',
  'ofdot-circle-o',
  'ofdownload',
  'ofdrivers-license (alias)',
  'ofdrivers-license-o (alias)',
  'ofedit (alias)',
  'ofellipsis-h',
  'ofellipsis-v',
  'ofenvelope',
  'ofenvelope-o',
  'ofenvelope-open',
  'ofenvelope-open-o',
  'ofenvelope-square',
  'oferaser',
  'ofexchange',
  'ofexclamation',
  'ofexclamation-circle',
  'ofexclamation-triangle',
  'ofexternal-link',
  'ofexternal-link-square',
  'ofeye',
  'ofeye-slash',
  'ofeyedropper',
  'offax',
  'offeed (alias)',
  'offemale',
  'offighter-jet',
  'offile-archive-o',
  'offile-audio-o',
  'offile-code-o',
  'offile-excel-o',
  'offile-image-o',
  'offile-movie-o (alias)',
  'offile-pdf-o',
  'offile-photo-o (alias)',
  'offile-picture-o (alias)',
  'offile-powerpoint-o',
  'offile-sound-o (alias)',
  'offile-video-o',
  'offile-word-o',
  'offile-zip-o (alias)',
  'offilm',
  'offilter',
  'offire',
  'offire-extinguisher',
  'offlag',
  'offlag-checkered',
  'offlag-o',
  'offlash (alias)',
  'offlask',
  'offolder',
  'offolder-o',
  'offolder-open',
  'offolder-open-o',
  'offrown-o',
  'offutbol-o',
  'ofgamepad',
  'ofgavel',
  'ofgear (alias)',
  'ofgears (alias)',
  'ofgift',
  'ofglass',
  'ofglobe',
  'ofgraduation-cap',
  'ofgroup (alias)',
  'ofhand-grab-o (alias)',
  'ofhand-lizard-o',
  'ofhand-paper-o',
  'ofhand-peace-o',
  'ofhand-pointer-o',
  'ofhand-rock-o',
  'ofhand-scissors-o',
  'ofhand-spock-o',
  'ofhand-stop-o (alias)',
  'ofhandshake-o',
  'ofhard-of-hearing (alias)',
  'ofhashtag',
  'ofhdd-o',
  'ofheadphones',
  'ofheart',
  'ofheart-o',
  'ofheartbeat',
  'ofhistory',
  'ofhome',
  'ofhotel (alias)',
  'ofhourglass',
  'ofhourglass-1 (alias)',
  'ofhourglass-2 (alias)',
  'ofhourglass-3 (alias)',
  'ofhourglass-end',
  'ofhourglass-half',
  'ofhourglass-o',
  'ofhourglass-start',
  'ofi-cursor',
  'ofid-badge',
  'ofid-card',
  'ofid-card-o',
  'ofimage (alias)',
  'ofinbox',
  'ofindustry',
  'ofinfo',
  'ofinfo-circle',
  'ofinstitution (alias)',
  'ofkey',
  'ofkeyboard-o',
  'oflanguage',
  'oflaptop',
  'ofleaf',
  'oflegal (alias)',
  'oflemon-o',
  'oflevel-down',
  'oflevel-up',
  'oflife-bouy (alias)',
  'oflife-buoy (alias)',
  'oflife-ring',
  'oflife-saver (alias)',
  'oflightbulb-o',
  'ofline-chart',
  'oflocation-arrow',
  'oflock',
  'oflow-vision',
  'ofmagic',
  'ofmagnet',
  'ofmail-forward (alias)',
  'ofmail-reply (alias)',
  'ofmail-reply-all (alias)',
  'ofmale',
  'ofmap',
  'ofmap-marker',
  'ofmap-o',
  'ofmap-pin',
  'ofmap-signs',
  'ofmeh-o',
  'ofmicrochip',
  'ofmicrophone',
  'ofmicrophone-slash',
  'ofminus',
  'ofminus-circle',
  'ofminus-square',
  'ofminus-square-o',
  'ofmobile',
  'ofmobile-phone (alias)',
  'ofmoney',
  'ofmoon-o',
  'ofmortar-board (alias)',
  'ofmotorcycle',
  'ofmouse-pointer',
  'ofmusic',
  'ofnavicon (alias)',
  'ofnewspaper-o',
  'ofobject-group',
  'ofobject-ungroup',
  'ofpaint-brush',
  'ofpaper-plane',
  'ofpaper-plane-o',
  'ofpaw',
  'ofpencil',
  'ofpencil-square',
  'ofpencil-square-o',
  'ofpercent',
  'ofphone',
  'ofphone-square',
  'ofphoto (alias)',
  'ofpicture-o',
  'ofpie-chart',
  'ofplane',
  'ofplug',
  'ofplus',
  'ofplus-circle',
  'ofplus-square',
  'ofplus-square-o',
  'ofpodcast',
  'ofpower-off',
  'ofprint',
  'ofpuzzle-piece',
  'ofqrcode',
  'ofquestion',
  'ofquestion-circle',
  'ofquestion-circle-o',
  'ofquote-left',
  'ofquote-right',
  'ofrandom',
  'ofrecycle',
  'ofrefresh',
  'ofregistered',
  'ofremove (alias)',
  'ofreorder (alias)',
  'ofreply',
  'ofreply-all',
  'ofretweet',
  'ofroad',
  'ofrocket',
  'ofrss',
  'ofrss-square',
  'ofs15 (alias)',
  'ofsearch',
  'ofsearch-minus',
  'ofsearch-plus',
  'ofsend (alias)',
  'ofsend-o (alias)',
  'ofserver',
  'ofshare',
  'ofshare-alt'
]
