export const CHANGE_PATTERN_SIZE = 'SETUP/CHANGE_PATTERN_SIZE'
export const CHANGE_PATTERN_PARTS = 'SETUP/CHANGE_PATTERN_PARTS'

export const LIST_BUTTON_CLICK = 'LIST/LIST_BUTTON_CLICK'

// export const GENERATE_PATTERN = 'PLAYER/GENERATE_NEW_PATTERN'
// export const GENERATE_PATTERN = 'PLAYER/PLAY_BUTTON'

// export const GENERATE_PATTERN = 'VIEW/MOUSE_HOVERED'

// export const GENERATE_PATTERN = 'LIST/PLAY_PATTERN'
