const TYPES = {
  'CHANGE_PATTERN_SIZE': 'SETUP/CHANGE_PATTERN_SIZE',
  'CHANGE_PATTERN_PARTS': 'SETUP/CHANGE_PATTERN_PARTS',
  'LIST_BUTTON_CLICK': 'LIST/LIST_BUTTON_CLICK',
  'PLAY_PATTERN': 'LIST/PLAY_PATTERN'
}

export default TYPES