export const blissNames = `
ATB,all-terrain_bike
ATM,cash_machine
A_(uppercase)
Abraham
Adam
Adar
Advent
Aegir
Afghanistan
Africa
Alice_(in_Wonderland)
All_Saints'_Day
Allah
Antarctic
April
Aquarius_(in_zodiac)
Arabic_(language)
Aries_(in_zodiac)
Ascension_(of_Christ)
Ascension_Day
Asia
August
Australia
Austria
Av_(Hebrew_month)
B_(uppercase)
Balder
Bangladesh
Batman
Belarus
Belgium
Bible_(Christian)
Bliss,Bliss_language,Blissymbolics
Bliss_(class)
Bliss_fanatic
Brahma
Brazil
Brontosaurus
Buddha
Buddhism
CD,record
CD
CD_cover
CD_player,record_player,stereo
CNS_injury
C_(uppercase)
Canada
Cancer_(in_zodiac)
Capricorn_(in_zodiac)
Ceres_(dwarf_planet)
Chanukah,Hanukkah
Cheshvan
Children's_Day
China
Christian_(person)
Christian_charity
Christian_event
Christian_faith
Christian_hope
Christian_love
Christianity
Christmas
Christmas_Eve_(day)
Christmas_Eve_(evening)
Christmas_pudding
Christmas_song,carol
Christmas_tree
Chumash,Pentateuch
Czech_Republic
DNA
DVD,movie_disc
DVD
DVD_player
D_(uppercase)
Danish_(class)
Danish_(language)
Danish_(language)_(OLD)
December
Denmark
Denmark_(OLD)
Dharma_wheel
Durga
E_(uppercase)
Earth,Tellus_(planet)
Earth_axis,axis
Eastern_Orthodox_Church
Egypt
Elul
England
English_(class)
English_(language)
Epiphany
Eris_(dwarf_planet)
Estonia
Estonian_(language)
Euro
Europe
Eve
F_(uppercase)
Family_Day
Father's_Day
February
Finland
Finnish_(class)
Finnish_(language)
Formula_One,NASCAR_Kart
France
French_(language)
French_fries,chips
French_fries,chips_(OLD)
French_horn,horn_(1)
French_horn,horn_(2)
Frey
Freya
Friday_(OLD)
Friday_(day5)
Friday_(day6)
Friday_(day7)
Frigg
GPS,satnav
GPS_(system)
G_(uppercase)
Ganesh
Gemini_(in_zodiac)
German_(class)
German_(language)
Germany
God
God_the_father
God_the_son
Good_Friday
Good_day_(bye)
Good_day_(hello)
Good_evening_(bye)
Good_evening_(hello)
Good_morning_(bye)
Good_morning_(hello)
Good_night_(bye)
Good_night_(hello)
Greece
H_(uppercase)
Haggadah
Halloween
Halloween_(OLD)
Hattifatteners
Havdalah
Heaven,Kingdom_of_God
Hebrew_(class)
Hebrew_(language)
Hemulen
Holy_City
Holy_Family
Holy_Infant
Holy_Spirit
Holy_Trinity
Host,wafer_(in_religious_ceremony)
Hugin_and_Munin
Hungary
I,me,myself-(feminine)
I,me,myself-(masculine)
I,me,myself
I_(uppercase)
I_need_more_time,give_me_time
Iceland
Icelandic_(language)
Independence_Day_(Israel)
India
Iran
Iraq
Ireland
Irish_(language)
Islam
Israel
Italian_(language)
Italy
Iyar
J_(uppercase)
January
Japan
Jerusalem_Day
Jesus_(of_Nazareth),Jesus_Christ,Christ
Jesus_Christ
Jew
Jewish
Joseph,Saint_Joseph
Judaism
July
June
Jupiter_(planet)
K_(uppercase)
Kabbalat_Shabbat
Kali
Kazakhstan
Kislev
Koran
L_(uppercase)
Lag_B'Omer
Lakshmi
Latvia
Latvian_(class)
Latvian_(language)
Lent
Leo_(in_zodiac)
Libra_(in_zodiac)
Little_My
Loki
Loki_(OLD)
MMS
MP3_player,iPod_(etc)
M_(uppercase)
March
Mars_(planet)
Mary_(Mother_of_Christ)
May
Megillah_(Book_of_Esther)
Mercury_(planet)
Messiah
Midgard's_serpent
Mjolnir
Monday_(OLD)
Monday_(day1)
Monday_(day2)
Monday_(day3)
Moominmamma
Moominpappa
Moomintroll
Moses
Mother's_Day
Muhammad,Mohammed,Muhammed
Muslim,Moslem,Islamic
Muslim,Moslem
N_(uppercase)
Neptune_(planet)
Netherlands_(The),Holland
New_Testament
New_Year's_Day
New_Year's_eve,end_of_year_(day)
New_Year's_eve,end_of_year_(evening)
New_Year's_eve_(day)
New_Year's_eve_(evening)
New_Year_(general)
Nisan,Nissan
Noah
Nordic_God,Nordic_Goddess
North_America
North_Pole
Norway
Norwegian_(language)
November
OK,alright
O_(uppercase)
October
Old_Testament
Olympics,Olympic_games
PEP_mask
P_(uppercase)
Passover
Pegasus
Persian_(language)
Pisces_(in_zodiac)
Pluto_(dwarf_planet)
Poland
Pope
Portugal
Pterosaur,Pterodactyl
Purim
Q_(uppercase)
R_(uppercase)
Ramadan
Resurrection_of_Christ
Roman_Catholicism,Roman_Catholic_Church
Romania
Romanian_(class)
Romanian_(language)
Rosh_Hashana
Russia
Russian_(language)
S_(uppercase)
Sabbath,day_of_rest
Saehrimnir
Sagittarius_(in_zodiac)
Sami(s)
Sandman
Santa_Claus,Father_Christmas
Saturday_(OLD)
Saturday_(day1)
Saturday_(day6)
Saturday_(day7)
Saturn_(planet)
Scorpio_(in_zodiac)
Scotland
September
Shavuot
Shevat,Shvat
Shiva
Sif
Simchat_Torah
Sivan
Sleipnir
Sniff
Snork
Snork_Maiden
Snufkin
South_Africa
South_America
South_Pole
Spain
Spanish,Castilian_(language)
Spiderman
Sukkot
Sunday_(OLD)
Sunday_(day1)
Sunday_(day2)
Sunday_(day7)
Superman
Sweden
Swedish_(class)
Swedish_(language)
Switzerland
T-shirt,tee_shirt,jersey
TV_programme,TV_show,radio_programme
TV_studio,radio_studio
T_(uppercase)
Take_your_time!
Tammuz
Tarzan
Taurus_(in_zodiac)
Tevet
Thai_(class)
Thai_(language)
Thailand
The_Groke
The_Nordic_countries
Thor
Thursday_(OLD)
Thursday_(day4)
Thursday_(day5)
Thursday_(day6)
Tibet
Tisha_B'Av
Tishri
Toffle
Torah
Triceratops
Tu_Bishvat
Tuesday_(OLD)
Tuesday_(day2)
Tuesday_(day3)
Tuesday_(day4)
Turkey
Tyr
Tyrannosaurus_Rex
USA
U_(uppercase)
Ukraine
Union_Jack_pattern
United_Kingdom
Universe
Uranus_(planet)
V_(uppercase)
Valentine's_Day
Valentine_(card)
Valhalla
Vatican,Vatican_City
Venus_(planet)
Viking
Viking_ship
Virgo_(in_zodiac)
Vishnu
W_(uppercase)
Wednesday_(OLD)
Wednesday_(day3)
Wednesday_(day4)
Wednesday_(day5)
Woden
X-ray-(to)
X-ray
X_(uppercase)
Y_(uppercase)
Yahrzeit
Yom_Kippur
Z_(uppercase)
a,an,any
a_(lowercase)
ability,capability,capacity,potential
ability_(half_sized)
aboard,on_board
abortion_(induced)
about,concerning,in_relation_to,of,on
abseiling,rappelling
absorbent_material,sponge
abstention
abstract
abuse,assault,violence
accept-(to)
access-(to)
accessibility,access
accessible
accessory
accident,chance_event
accident
accordion
account
accusation
accusation_(legal),charge,prosecution
accuse-(to)
accuse_(legal),charge,prosecute-(to)
ache
achieve-(to)
achievement
acne
acquiring,getting,receiving
acrobat
acrobatics
across
act,demonstrate_(against)-(to)
act,demonstrate_(in_favour_of)-(to)
act_in_favour_of_(legal)-(to)
action,act,deed
action,demonstration_(against)
action,demonstration_(in_favour_of)
active,actively
activity,male_gender_(in_combinations)
activity_centre
activity_centre_(children)
activity_centre_(leisure_time),after_school_club,youth_club
activity_centre_(teenagers)
actor
acupuncturist
add,gain-(to)
addict
addiction
adding,additive
addition,gain
address
adjective
adolescence
adopt-(to)
adoption
adult,grownup
adult,mature
advance,go-(to)
adventure
adventure_(OLD)
adventurous
adverb
adversity,hardship,setback
advertisement
advice,counsel,recommendation
advise,counsel,recommend-(to)
advocacy,representation_(legal)
advocacy
advocate-(to)
advocate
advocate_(legal)-(to)
advocate_(legal)
advocate_(legal,speaking)
advocate_(speaking),spokesperson
aerial,antenna
affix
afraid,frightened,scared
after,behind
afternoon
again
against,opposed_to
age
agenda
agnosticism
ago,then_(past)
agree-(to)
agreed,in_agreement,harmonious
agreement
agreement_(spoken)
agreement_(written),contract
aid,device,support
aid_store_room
air,atmosphere
air_traffic_controller
airforce,air_force
airplane,aeroplane,plane
airport
airport_terminal
ajar
alarm
alcohol,ethanol
alcohol_abuse,alcohol_addiction
alcoholic_drink,alcoholic_beverage,liquor
alcoholism,alcohol_addiction
alive
all,every,everything,total,whole
all_gone
all_knowing
all_powerful
allergy,hypersensitivity
alligator,crocodile
alone,just,only,solitary
along_with
alpana,rangoli_(decoration)
alphabet,letters_(lowercase)
alphabet,letters_(uppercase)
altar
altar_cloth
alternate-(to)
alternating
alternating_current,AC
alternation
although
altimeter
alto
altruism,selflessness
aluminium_foil,tin_foil
always,ever,forever
ambulance
amen
amenorrhea
ammeter
among,amongst
amphibian
amplifier_(1)
amplifier_(2)
amplitude
ampullae
amuse,entertain,please-(to)
anaesthesia,numbness
anaesthetic
anal_intercourse
ancestor
anchor
and,also,plus,too
anemometer
angel_(1)
angel_(2)
angel_(OLD)
angle
angle_(measurement)
angle_(right),right_angle
angry,angrily,mad
animal,beast
animal_(bovine,ovine),bovid,bovine
animal_(bushy_tailed)
animal_(cold-blooded),cold-blooded_animal,poikilotherm,ectotherm
animal_(protected)
animal_(warm-blooded),warm-blooded_animal,homeotherm,endotherm
animal_(water)
animal_(wild)
animal_droppings
animal_skin,hide,pelt
ankle
ankle_splint
anniversary
answer,reply-(to)
answer,reply
ant
anthropologist
anthropology
anti-virus_program
anus
anxiety
anxious,anxiously
any_day,someday
anyone,anybody,somebody,someone
anything,something
anytime,sometime
anywhere,anyplace,someplace,somewhere
apartment,flat,unit
apartment_block
apologize,apologise,regret_(express)-(to)
aport
apostle
apostrophe
apparent(ly),clear(ly),evident(ly),obvious(ly),plain(ly)
appear-(to)
appearance,manifestation
appendix,cecum,caecum
appetizer,starter,entree
applaud,clap-(to)
applause,clapping
apple
appointment
appreciate,value,treasure-(to)
approach
approve-(to)
apricot
apricot_(dried)
apron,coverall,smock,overall
archeologist
archeology
archery
archipelago
architect
area_(measurement)
argue,dispute,quarrel-(to)
argument,dispute,quarrel
arm
armchair
armed
armoured_force,tank_force
army,regular_army,ground_forces
aroma_therapist
around
arrest-(to)
arrow
arrow_(bent)
art
art_gallery,gallery
arthropod(s)
article
artificial_insemination
artificial_respiration
artillery
artist
ascending_and_descending
ashes
ashore
ashtray
ask,inquire,question-(to)
asleep
asparagus
assessment_room
assistance_dog
astarboard
asteroid
astrologer,astrologist
astrology
astronaut,cosmonaut
astronomer
astronomy
at
at_one's_destination,there
atheism
athletics
atlas,book_of_maps
atom
attach_(computer)-(to)
attached_(computer)
attachment,appendix,annex
attachment_(computer)
attack-(to)
attack
attack_(of_illness)
attempt,effort,try
attendance_list,register_list,contact_list
attention
attic
audio_book
audiologist
auditor,accountant
auditory_system
aunt
autoharp,zither,kantele
autumn,fall
autumn,fall_(ckb)
avalanche
avocado
awake
away,at_a_distance,off
away,at_a_distance,off_(OLD)
awful,dreadful,terrible
b_(lowercase)
baby,infant
baby_animal
baby_bottle,feeding_bottle
baby_boy
baby_carriage,buggy,pram,pushchair,stroller
baby_clinic
baby_girl
babysitter
back_(body)
back_and_forth,backward_and_forward,to_and_fro
back_up-(to)
backpack,rucksack
backspace_(computer)-(to)
backward,back
bacon
bacterial_infection
bacterium
bad,wrong
bad_conscience
badge,shield
badger
badminton_(activity)
badminton_(sport)
bagel
baggage,bag,luggage,suitcase
bagpipe
baguette
bake,cook,roast-(to)
baker
bakery
baking_powder
baking_tin,baking_pan,ovenware
balance,sense_of_balance
balance_(general),poise-(to)
balance_(general),poise
balance_(walking,standing)-(to)
balcony,porch,veranda
ball
ball_field
ball_pool
ball_sports
ballet
balloon
balloon_(hot_air)
ballooning
ballot,voting_slip
banana
band,orchestra
band,orchestra_(OLD)
band_(of_frequencies)
band_(of_frequencies)_(OLD)
bandage,dressing
bandit,armed_robber
bandy_(sport)
banjo
bank
bank_card,money_card
bar,cake
bar,pub
bar_mitzvah_(Hebrew)
barber,hairdresser
barbershop,beauty_shop
barge,river_boat
bark-(to)
bark
barley
barn,stable,shed
barn
barometer,manometer
barred_window
barrier_(contraceptive)
barrow,garden_cart,wheelbarrow
barrow,grave_mound
base_camp
baseball_(activity)
baseball_(sport)
basement,cellar
basketball_(activity)
basketball_(sport)
bass
bass_clarinet
bass_guitar
bassoon_(1)
bassoon_(2)
bat_(animal)
bat_(sport)
bat_mitzvah_(Hebrew)
bath,washing
bathing_rule(s)
bathroom,washroom
bathtub,bath,tub
batter
battery
bazaar
be,am,are,is,exist-(to)
be_caused_by-(to)
be_cold-(to)
be_named,be_called-(to)
be_patient-(to)
beach,bank,coast,shore
beach_tennis_(activity)
beach_tennis_(activity)_(OLD)
beach_tennis_(sport)
beach_tennis_(sport)_(OLD)
bean
bean_(dried),chick-pea,kidney_bean,pinto_bean
bear's_head
bear
beard
beautiful,attractive,good-looking,handsome,pretty
beauty
beaver
because
become-(to)
bed
bedbug,wall_louse
bedroom
bedtime
bee,bumblebee,hoverfly
beef
beer
beet,beetroot
beetle
before,in_front_of,prior_to
beg,plead-(to)
beggar
begin,start-(to)
beginning,start
beginning_of_year
behaviour
beige
being_(state_of)
belief
belief_(supernatural)
believe-(to)
believer
believer_(in_God)
bell,chime_bar
bell
bells,chime_bars,tubular_bells
belongs_to,of_(possessive)
belt,sash
bench,pew
bend-(to)
berry
berth,bunk
beside
best
bet-(to)
bet
better
betting
between
beyond,past
beyond,past_(OLD)
biathlon
bib
bicycle
bicycle_helmet,crash_helmet
bicycle_path
big,large
bigness,largeness
bike_lamp
billiards
bindi,tika_(decoration)
binoculars,field_glass
binoculars,field_glass_(OLD)
biochemical_product,organic_compound
biochemist
biochemistry
bioenergy
biologist
biology
biology_(class)
biomass,biofuel
birch
bird
bird_(domestic)
bird_(protected)
bird_(wild)
bird_nest,birdnest
bird_of_prey,raptor_falcon,hawk,eagle
birdfeeder,bird_table
birdhouse,house_for_bird
birth,giving_birth,parturition,delivery
birth
birth_control
birth_control_pill,pill
birthday
bisexual
bisexuality
bishop
bit_(horse)
bite-(to)
bite
bitter
black_(bci)
black_(ckb)
blackberry
blackbird,crow,raven
blackboard,chalkboard,whiteboard,writing_board
blacksmith
bladder
blanket,duvet,quilt
bleat,baa-(to)
bleed-(to)
bless-(to)
blind
blindness
bliss-name
blissymbol,Bliss-word
blissymbol_part
blissymbolics_resource_centre
block,brick
block,city_block
blog,web_blog
blood
blood_circulation
blood_pressure
blood_vessel
blot
blow_(mouth)-(to)
blow_(wind)-(to)
blue_(bci)
blue_(ckb)
blueberry
bluebird
blush-(to)
boar
board,board_of_directors,executive
board-(to)
board
board_(material)
board_and_lodging,room_and_board
boarding,embarkation_(to_sea)
boat,ship
boat_ladder
boathouse
boating
bobsleigh
body,trunk
body_brace,corset
body_fluid
body_hair
body_painting
body_part
body_temperature
body_with_mane
body_with_navel
body_with_pubic_hair
boil_(food)-(to)
boil_(liquid)-(to)
bolt_(horse)-(to)
bomb,explosive
bomb_shelter
bone
bone_fracture
bones_with_joint
bonfire,barbeque,campfire
bongo_drum,hand_drum
book
bookshop
boom
boot,trunk,roof_box,luggage_compartment
boot
bored
boring,dull,depressing
borrow-(to)
boss,supervisor
boss,supervisor_(OLD)
botanist
botany
both
bottle,flask
bottle_nipple,teat
bottle_opener
bottleneck,bottle_opening
bottom,base
bottom,bottom_of_a_thing
boules,boccia_(sport)
bouquet_(flowers)
bow,arc
bow,fore
bow
bow_(knot)
bow_(musical_instrument)
bow_and_arrow
bow_and_string_(musical)
bow_and_string_instrument
bowel,intestine_(OLD)
bowel_movement,defecation,shitting,feces,shit,poop
bowling_(activity)
bowling_(sport)
box,cube
boxing_(activity)
boxing_(sport)
boy,lad
boyfriend
bra,brassiere
brace(s)_(dental),dental_brace(s)
brace(s)_(dental),dental_brace(s)_(medical)
brace_(neck,medical),neck_brace,cervical_collar,neck_collar
bracelet
bracha,berakah,prayer_(small)
braid,plait,pigtail(s)
braid,plait-(to)
brain
brain_injury
brain_signal
brake_(general)-(to)
brake_(general)
brake_(vehicle)-(to)
brake_(vehicle)
branch
brass_instrument
brave,courageous
bread,loaf_of_bread,loaf
bread_(sliced),sliced_bread
bread_crust
bread_knife
bread_surface
bread_with_fruit
bread_with_seeds
break,crack,fracture,tear,injure,damage-(to)
break,fracture,injury,damage
breakable,fragile,vulnerable
breakfast
breast(s)
breastbone,sternum
breath,breathing,respiration
breathe-(to)
breathing_aid
breeze
bricklayer
bridge,overpass
bridle,headstall
briefcase
bright
bring-(to)
broadband
broadband_(OLD)
broadcast,transmit-(to)
broccoli
broil,barbecue,grill-(to)
broken,injured,damaged
bronze
bronze_age
brooch
brook,creek
broom
brother-in-law_(husband's_brother)
brother-in-law_(partner's_brother)
brother-in-law_(wife's_brother)
brother
brown_(bci)
brown_(ckb)
brownie,house_elf
bruise,contusion,haematoma
bruise,dent
bruised,dented
brush-(to)
brush
brush_teeth-(to)
brussels_sprout(s)
bubble
buddhist
buddhist_(person)
budget,business_plan
buffalo,bison
bugle_(1)
bugle_(2)
bugle_(hunting)
build,construct-(to)
building_with_attic
building_with_cellar
building_with_chimney
building_with_foundation
building_with_storey
building_with_yard_and_fence
buildings_with_courtyard
bulb_(flower)
bulb_(plant)
bulbous_plant
bull
bull_(fighting)
bump,press,pressing
bump,press-(to)
bun_(food)
bun_(soft),roll_(soft),scone,brioche
burial
burial_(religious)
burial_mound,grave_mound
burial_site
burn-(to)
burnable,combustible,ignitable
burned,burnt
burned_out,burnt_out
burned_out,burnt_out_(OLD)
burning
burp,belch-(to)
bury-(to)
bury_(person)-(to)
bus,coach
bus_driver
bus_lane
bus_station
bus_stop,bus_bay
bus_stop,bus_bay_(OLD)
bush,shrub
business,economy,commerce,trade
business_idea
but,except
butcher
butcher_shop
butter
butterfly,moth
buttocks,bottom,bum,rear,ass
buttocks_and_genitals
button,gripper,snap
buy,purchase-(to)
buzzer
by,by_means_of,of
c_(lowercase)
cabbage
cabin,cottage,hut
cabin_(airplane)
cabin_(boat)
cable_car
cactus
cactus_fruit_(dragon_fruit,cherimoya)
caesarean_section,C-section
cafe,coffee_house,snack_bar
cage
cake,bread_with_sugar
calculate-(to)
calculator
calendar
call,telephone,ring-(to)
calling,profession,career
calling,vocation
calm,lull
calm_(weather)
camel
camera
camp
camper,caravan,mobile_home
camper_van,RV
camping_mat,sleeping_mat
camping_stove
can,be_able-(to)
can,tin,jar
can_opener
canal_(water)
cancer
candle
candy,sweets
candy
candy_(OLD)
candy_(liquorice)
candy_bar
cane,stick,walking_stick
cannabis
cannon,gun
cannula_(with_needle)
canoe
canoeing
canter-(to)
cap
cape,poncho,clothing_without_sleeves
capital,capital_city
capture,catch,seize-(to)
car,automobile,motor_vehicle
car_light(s)
car_mechanic
car_racing,auto_racing
car_track
card
card_game
cardboard,paperboard
cardiac_arrest
cardiologist
cardiovascular_system
cards,playing_cards
care,protect,defend-(to)
care,protection,defence
care_centre
care_manager,care_plan_manager
careful
caregiver,protector,defender
carnivore
carpenter
carpentry,wood_work
carriage
carriage_racing
carrot,vegetable_(wedge-shaped)
carry,move,transport-(to)
carrycot,bassinet
cart,carriage
cartographer
cartography
cartoon,animated_picture
carve-(to)
case,casing
casserole
cassette,audiocassette,videocassette
castanets_(1)
castanets_(2)
castle,palace
castle,palace_(royal)
cat,feline_(animal),felid
catamaran,pontoon_boat
catch,grab-(to)
caterpillar
catheter_(urine)
cauliflower
causality
cause-(to)
cause
cave
cavity,caries
cease-fire,armistice
ceiling
celebration
celebration_of_life
celeriac,celery
celery
celibacy,chastity,abstinence
celibacy,chastity
celibacy_(religious)
cell
cello
cellular_fluid
cemetery
cent
central_nervous_system,CNS
century
ceramics,pottery
cereal
ceremony
certain,sure
certain_(OLD)
cervix
chain
chair,seat
chairlift
chairman
chalice
challah
challenge
chameleon
champagne
chance,risk
change,alter,convert-(to)
change,alteration,conversion
channel_(programs)
character_(in_a_story)
charge_(electricity)-(to)
charged_(electricity)
charger,battery_charger
charity
charm
charming
chase-(to)
chase
chat_(online)-(to)
chat_(online)
cheap,inexpensive
cheap_(OLD)
cheat-(to)
cheating
checked
cheek
cheer-(to)
cheering_(the_sound)
cheerleader
cheers_(toast)
cheese
cheetah
chemical_product
chemist
chemistry
chemistry_(class)
cherry,cherries
chess
chest
chest_hair
chest_of_drawers,bureau,dresser
chew-(to)
chewing-gum
chick
chicken_(bird)
chicken_(food),poultry
child,kid,youngster
child_abuse
child_care
child_harness,walking_reins
children's_room
children's_song,nursery_rhyme
children’s_rights
chilly
chimney
chin
chip_shop
chipmunk
chiropractor
chirp,twitter-(to)
chive
chocolate,cocoa,cacao_(bitter_powder)
chocolate,cocoa,cacao_(sweet_powder)
chocolate
chocolate_(OLD)
chocolate_(hagel)
chocolate_bar
chocolate_drink
chocolate_drink_(OLD)
chocolate_flavouring,cocoa,cacao_powder_(OLD)
chocolate_flavouring
chocolate_sauce
chocolate_spread
chocolate_spread_(OLD)
choice,selection,election
choir,chorus
choke,gag-(to)
choose,pick,select-(to)
chop-(to)
chopstick(s)
christian
chromosome
chronic_fatigue_syndrome
chronic_fatigue_syndrome_(OLD)
church,mosque,temple
church_ruin,temple_ruin,wreck,wreckage_(church,temple,mosque)_(1)
church_ruin,temple_ruin,wreck,wreckage_(church,temple,mosque)_(2)
cider
cigarette
cinnamon
cinnamon_(powder)
cipher
circle_(shape)
circulatory_system
circumcision
circumcision_ceremony
circus
citizen
city,metropolis
city_tour
civil_engineer
clarinet,reed_instrument_(1)
clarinet,reed_instrument_(2)
class
classmate
classroom
claw_(animal)
claw_(bird)
claw_(shellfish)
clean-(to)
clean
clean_(OLD)
cleaning_cloth
cleaning_tool
clear,transparent
clearness,clarity,transparency,transparence
clerk,legal_aid
clerk
client,customer
climate
climb-(to)
clinic
clitoris
cloakroom,walk-in_closet
clock,timepiece
close,enclose,shut-(to)
closed
cloth,fabric,material,textile,net
clothes_line,drying_line
clothing,clothes,garment
clothing_shop
cloud
cloudberry
cloudy
clown
club
clue
co-housing
coarse_slang
coat,jacket,jumper,sweater
cockerel,rooster
coconut
cod,codfish
code,password
coffee
coffin
coin
cold,common_cold
cold
cold_(opposite_hot)
coldness,cold
collar
collarbone,clavicle
colleague
collection,pile,tussock_(etc)
colon
coloring_book
colour
comb-(to)
comb
combination,connection
combine,connect,link-(to)
combine_(harvester)
combine_marker
come,approach-(to)
comedy
comet
comfort,console-(to)
comfortable,restful
comma
command,order-(to)
commandments
common,mutual,shared
communicate-(to)
communication
communication_impaired
communication_impairment
communication_satellite
communication_therapist
community_centre,town_hall,village_hall
commuter_train
comparative_more
compare-(to)
compartment
compass
compass_(drawing)
compete,race-(to)
composer
compost
compression,compressing,squeezing
computer
computer_(OLD)
computer_case
computer_game_(OLD)
computer_peripheral
computer_screen,monitor
concept
conception,fertilization,fertilized_egg
conceptualise-(to)
concert
concert_hall
concrete,cement
concrete
condensation
condense-(to)
condom
conductive_education
conductor_(music)
conductor_(music)_(OLD)
conductor_(teacher,therapist)
cone,conifer_cone,strobilus
cone
confess-(to)
confirmation
confusion_(feeling)
confusion_(mental)
congratulate-(to)
congratulations,best_of_luck,mazel_tov
conjunction
conjure,turn_to,transform-(to)
connection_(computer)
connector,interface_box
conscience
consciousness,awareness
considerate,thoughtful
consideration,thoughtfulness
constellation_of_stars
constipation_(1)
constipation_(2)
constitution
constructional_blocks,lego_(etc)
constructional_toy
contact_sports
container,basket_(high)
container,bowl,holder,pouch,basket
container_(low)
continent
continental_drift
continuance,continuation
continue,pass-(to)
contrabassoon,double_bassoon_(1)
contrabassoon,double_bassoon_(2)
contrast-(to)
control
control_(OLD)
control_oneself-(to)
control_tower
conversion_(belief)
convert_(belief)-(to)
cook,chef
cook-(to)
cookbook,cookery_book
cookie,biscuit
cookie_jar,biscuit_tin
cooking,cookery,preparation_(general)
cooking,cookery,preparation_(hot_food)
cooking_vessel,pots_and_pans
cool,chilly
cool,chilly_(opposite_warm)
copier,photocopier
copper
copy,duplicate
coral
coral_reef
cordless_phone
core_activity
corkscrew
corn
corn_syrup
cornea
corner
corner_(room)
cornmeal
corpse,cadaver,carrion
correct,accurate,good,right
correct_thinking
correctness
corridor,hall
corruption
corruption_(OLD)
cost,price
cost-(to)
costume,disguise
cottage_cheese
cotton
cotton_fabric
couch,chesterfield,sofa
cough-(to)
counsellor,adviser
count-(to)
count
country,state
country_music
countryside,country,nature
coup,coup_d'etat
coup,hijack,takeover
couple_(female)
couple_(heterosexual)
couple_(male)
couple_(two_persons)
courage
courgette,zucchini
court,courthouse
court,courtroom
court,field
court,field_(OLD)
cousin
cousin_(female)
cousin_(male)
covered,hidden
cow
coward
cowardice
cowardly
cowshed
crab,shellfish_(with_claws)
crack,gap,cleft
craft
cramp,spasm
cranberry
crane
crash_(air),plane_crash,air_crash_(OLD)
crash_(car),car_crash_(OLD)
crash_(downward)-(to)
crash_(downward)
crash_(forward)-(to)
crash_(forward)
crater
crawl-(to)
crayfish
crayon,coloured_pencil,marker
cream
create-(to)
creation,nature
creative
creature,being
credit
credit_card
cremate-(to)
cremation
crescent
crew,staff
crew_(boat)
crew_(plane)
cricket
crime
criminal_(person)
criminality,crime
critic,evaluator
croak_(frog)-(to)
crochet-(to)
croquet_(activity)
croquet_(sport)
cross,Christianity_(in_combinations)
cross-(to)
cross_(a)
cross_country_skiing
crossed_racquets_(OLD)
crotch
crown
crown_(currency)
crown_prince
crown_princess
cruelty,mercilessness,ruthlessness
cruise_ship
crumbs
crush,squeeze-(to)
crutches
cry,weep-(to)
cry_out,call-(to)
crystal
cucumber
cuddle-(to)
culture
cup
cupboard,closet,wardrobe
cupcake,fancy_cake,pastry
cure-(to)
curiosity,curiousness,inquisitiveness,wonder
curious,inquisitive
curling
currant(s)
currency
current
current_events
curry
curry_(powder)
curry_sauce
curtain(s),drape(s)
curve,curved_line
cushion
cushion_(seat)
cut_(knife)-(to)
cut_(scissors)-(to)
cut_and_paste_(computer)-(to)
cutlery
cycle,ride_a_bike-(to)
cycle_of_life,life_cycle
cycling
cylinder,can
cylinder_for_breathing
cymbal
d_(lowercase)
dairy
dance,dancing
dance-(to)
dance_music
dance_therapist
dancing_therapy
danger
dangerous
dare-(to)
dark
dark_(OLD)
darkness
dart
darts
data_(digital_information)
date_(fruit)
date_(man_woman)
date_(two_persons)
daughter-in-law
daughter
day
day_and_night
day_before_holiday
day_care_centre
day_centre
daycare
dead,deceased
dead_(the_dead)
dead_person
deaf
deafness
dear
death
debarkation,disembarkation_(ashore)
decade
decide-(to)
decision
deck
decorated_cake
decoration,ornament
decoration_(OLD)
decrease,reduce-(to)
deep-fry-(to)
deep
deep_fryer
deer,cervine_(animal),cervid
defence_(legal)
defence_(spoken)
defend_(legal)-(to)
defend_(speak)-(to)
defend_(speak,legal)-(to)
definite
definition
deflate,let_out_air-(to)
deflation
degree
delete_(computer)-(to)
deletion,cancellation,destruction
delicacy,speciality_(food)
delicious,scrumptious,yummy
demand-(to)
democracy_(OLD)
democracy_(country)
democracy_(general)
den,lair
dense,thick,compact,tight,jammed
density,denseness,compactness,tightness_(general)
density,denseness,concentration_(measurement)
dental_floss
dentist
deodorant
department_store
departure
dependency
dependent
depression
depth
descend,go_down-(to)
describe-(to)
desert
designer,planner
desirable
desk,worktable,work_table
desktop_computer
dessert
destroy,annul,cancel,cross_out,delete-(to)
destroyed,ruined,demolished,deleted,erased,cancelled
detach,take_apart-(to)
detachment,separation,breakup
detective,investigator
detest,despise-(to)
develop-(to)
development
devil_(1)
devil_(2)
devoted
devotee,fan
devotion
dhoti,lungi
diagnosis_(medical)
diamond_(character)
diamond_(shape),rhombus,rhomb
diaper,nappy
diaphragm,midriff
diaphragm_(contraceptive),pessary
diarrhea,diarrhoea
dice,die
dichotomy,duality
dictator_(OLD)
dictator_(general)
dictatorship_(country)
dictatorship_(general)
dictionary,lexicon,wordbook
die-(to)
diet-(to)
diet
different,other,difference
different,other,unequal
difficult,hard
difficulty
dig-(to)
digest-(to)
digestion
digging,excavation
digital
digital_device
digital_game,video_game,computer_game
digital_memory,RAM
digital_memory,digital_storage
digital_processing,artificial_intelligence,calculation
digital_signal
digital_space_(limited)
digital_storage_device
digital_world
digits_(computer)
dilemma
dining_room
dinosaur
dinosaur_(OLD)
direct_current,DC
direction,cardinal_point
dirt,soil
dirty,soiled
disability,handicap,impairment
disability,handicap,impairment_(OLD)
disability_benefit
disability_benefit_(OLD)
disabled,handicapped_(intellectually,mentally)_(OLD)
disabled,handicapped_(physically)_(OLD)
disabled,impaired,handicapped_(intellectually,mentally)
disabled,impaired,handicapped_(physically)
disagree,discord,disaccord-(to)
disagreement,discord
disappear-(to)
disappearance
disappointed
disappointing
disappointment
disaster,catastrophe
disc,disk
disco
discomfort
discordant
discount
discount_sale
discount_store
discover-(to)
discovery
discus
discuss,converse,debate-(to)
discussion,conversation,debate,chat
disembark-(to)
disgust
disgusting_(general)
disgusting_(taste)
dish,plate,platter
dish_gloves,rubber_gloves
dish_rack
dishwasher
disinfectant,antiseptic
dislike-(to)
dislike
disperse,disseminate,scatter,spread-(to)
dispersion,dissemination,scattering,spread,spreading
distance
distance_(OLD)
district,area,neighbourhood_(country)
district,city_district,neighbourhood_(town)
disturbance,unrest
diver_(active_under_water)
diver_(jump)
diversity,variety_(general)
divide-(to)
divided
divine,holy
diving,activity_under_water
diving_(sport)
diving_equipment,diving_gear
division
divorce-(to)
divorce
dizzy
do,act-(to)
doctor,physician
doctor_(rehab,hab)
document,written_record
document_(electronic),digital_document
dog,canine_(animal),canid
dog_sled
dogsled_sport,dogsled_racing
doll
doll_pram,doll_carriage
dollar
dollhouse,doll_house
dolphin,porpoise,water_mammal_(with_tail)
domestic
domestic_animal
domestic_science,home_economics
domestic_science,home_economics_(class)
domino
donkey,mule
door
doorway,gate
dormouse_(sleepy_rodent)
dot
dotted
double_bass,bass_fiddle,contrabass
doubt,uncertainty
doubt-(to)
dough
doughnut
dove
down,downward
downhill_skiing
download-(to)
download
downward_and_backward
downward_and_forward
dragon
drain,sift,strain-(to)
drama
draw,sketch-(to)
drawer
dream-(to)
dreidel_top
dress,wear-(to)
dress
dress_up,disguise-(to)
dressage
dressing_gown,housecoat,robe
dribble-(to)
dried
dried_bean_(OLD)
drill
drilling_rig_(gas)
drilling_rig_(oil)
drilling_rig_(water)
drink,beverage
drink-(to)
drink_mix,shake,smoothie
drive-(to)
driver,chauffeur
driving_license
dromedary
drop
drop_anchor-(to)
drown-(to)
drown_(cause_to)-(to)
drowning
drug,mind-altering_drug
drug_(leaf_based)
drug_addict
drug_addiction
drug_dependency
drugstore,pharmacy
drum_(1)
drum_(2)
drumstick
drunk
dry-(to)
dry-(to)_(OLD)
dry
dry_(OLD)
drying_cupboard,airing_cupboard
drying_rack
drying_rack_(cloth)
drying_rack_(fish)
drying_room,drying_chamber
dryness,drought
dual
duck,bird_(water),waterbird,waterfowl,seabird,seafowl
duck_(food)
dump,dispose-(to)
dump_truck,dumper,tipper_lorry,tipper
dumpling
during,while
dust_storm,duster,sirocco
duty,obligation
dwarf,gnome
dwarf_planet
dyscalculia
dysgraphia
dyslexia
dystonia
e-book,digital_book
e-mail,email
e-mail_address,email_address
e_(lowercase)
each,every
each_other,one_another
eager,keen,willing
eagerness,keenness,willingness
ear,spike,capitulum
ear
ear_bone,ossicle,auditory_ossicle
ear_mold
eardrum,tympanic_membrane
early
earmuffs_(general)
earmuffs_(protection)
earn-(to)
earphones,headphones
earring
earth,globe,world
earth,ground,land
earthquake
earwax
ease,easiness,simplicity
east
easter
eastern
eastward
easy,easily
easy_(OLD)
eat-(to)
eating_disorder
eaves
economics
economics_(class)
economist
ecstasy
ecstatic
edge
edible,eatable
education,didactics,pedagogy
education
educationalist,educationist_(academic)
eel
effect,result
egg,ovum_(1)
egg,ovum_(2)
egg_(boiled),boiled_egg
egg_(fried),fried_egg
egg_(poached),poached_egg
egg_white,white_of_egg,albumin,glair
egg_yolk,yolk
eggplant,aubergine,brinjal
eggshell
eight_(digit),8
eight_(index_number)
either
ejaculation
elbow
elbow_pad
elbow_splint
electorate
electric,electrical
electric_circuit
electric_conductor
electric_conductor_(OLD)
electric_current
electric_field
electric_insulator,electrical_insulator
electric_kettle
electric_light,lamp
electric_pan
electric_piano
electric_toothbrush
electric_wheelchair
electric_wire,electric_cord,cord,cable,lead
electric_wire,electric_cord,cord,cable,lead_(OLD)
electrical_engineer
electricity
electricity_meter
electro_magnet
electromagnetic_radiation
elementary_school,primary_school
elephant
elevator,lift
elf_(fog)
elf_(star)
embark,board-(to)
embarrassed
embarrassing
embarrassment
embryo
emergency
emergency_call,emergency_telephone
emergency_room_(medical)
empathy
employed,working
employee
empower-(to)
empower-(to)_(OLD)
empowered
empowered_(OLD)
empowerment
empowerment_(OLD)
empty,evacuate,throw_away,void-(to)
empty-(to)_(OLD)
empty
empty_(OLD)
emptying,voidance,evacuation
enclosure
encourage-(to)
encouragement
end,arrival,stop
end_of_year
endangered
endlessness
endocrine_system
energy
energy_(mental)
energy_(physical)
engaged
engagement
enjoy-(to)
enormous
enough
enter,absorb,insert,penetrate-(to)
enter_(computer)
envious
environment
environs
epidemic
epiglottis
equal,same
equal-(to)
equality_(social)
equator
equestrian_sports
equilateral_triangle
equipment,gear
erection,erect_penis
error,mishap
erupt-(to)
eruption
escalator,moving_stairs
escape-(to)
escape
espionage,spying
eternal
eternal_(OLD)
eternal_life,immortality
eternal_life,immortality_(after_death)
eternity,infinity
eternity,infinity_(OLD)
etrog
evaluate-(to)
evaluation,value
evaluation,value_(half-sized)
evangelise-(to)
evangelise_(christian)-(to)
even_number
evening
evening_before_holiday,evening_of_Sabbath
event,happening,occasion
ever,whenever
evergreen_tree,spruce,fir,fir_tree
everybody,everyone
evidence
ewe
examination,investigation
examine_(medically)-(to)
excavator,digger,power_shovel
excellence
excellent
exchange,substitute,trade-(to)
exchange,substitution
exchanger
excitement
exciting,excitingly,excited,excitedly
exclamation_mark
exclude-(to)
excuse-(to)
excuse
exercise,work_out-(to)
exercise_(physical)
exhausted,worn_out
exhausted,worn_out_(OLD)
exhibition_hall,showplace
exhibitionism,immodesty,indecent_exposure
existence,being_(1)
exit-(to)
expect,anticipate-(to)
expectation,anticipation
expensive
expensive_(OLD)
experience
experiment-(to)
experiment
explain,give_a_reason-(to)
explanation,reason
explode,blow_up,detonate,burst-(to)
exploded
exploration
explore-(to)
explorer,enquirer
explosion,detonation,blowup
explosive
export-(to)
export
export_(computer)-(to)
exported
expose_oneself_indecently-(to)
external_hard_drive
extinction,extinguishing_(fire)
eye
eye_makeup
eye_mouse,eye_gaze
eye_with_eyebrow
eyebrow
eyebrow_pencil
eyelid(s)
eyelid_(lower)
eyelid_(upper)
eyeliner,kohl
f_(lowercase)
fable,allegory,parable
face
face_painting
face_with_beard
face_with_pimple
facial_hair
fact
factory,plant
fail-(to)
failure
faint,pass_out-(to)
fainting,absence
fairy,fairy_godmother
fairy_tale
falafel
fall,drop,spill,tumble
fall-(to)
fall_asleep-(to)
fallopian_tube
family,couple
family,couple_(female)
family,couple_(male)
family
family_(cohabiting)
family_(female)
family_(group_home)
family_(male)
family_(traditional)
family_planning
family_planning_clinic
fan
fan_(machine)
fan_club
fanatic
fanatic_(person)
fantasy,phantasy,imagination,illusion
far,distant,remote
far,distant_(OLD)
farfalle
farm
farmer
farmhouse
farness,remoteness,farawayness
farness,remoteness,farawayness_(OLD)
farrier
fart,wind
fashion_designer
fast,go_without_food
fast-(to)
fast_day
fast_food
fasten,attach,join,append,connect-(to)
fastener,gripper,velcro,zipper
fat,thick
fat,thick_(OLD)
fatal,lethal
father,dad,daddy,papa,pa,pop
father-in-law_(partner's_father)
fatness,thickness
fatness,thickness_(OLD)
favourite
fax-(to)
fax
fax_(machine)
fear,be_afraid,dread-(to)
fear,fright,concern
fear_of_heights,acrophobia
feather
fee
feed-(to)
feeding_tube
feel-(to)
feeling,emotion,sensation
female,feminine_(person)
female_(gender)
female_friend
fence,wall
fencing
ferry
fertile
fertility_counselling
fertilized
fetus
fever,temperature
few,little
few,little_(OLD)
fewer,less
fewest,least
fiance,groom-to-be
fiancee,bride-to-be
fiber,fibre,fibril,filament,strand
fidelity,loyalty,solidarity
field
field_hockey,hockey_(activity)
field_hockey,hockey_(sport)
fight,combat-(to)
fight,combat
figure_skating
file,data_file_(digital)
fill-(to)
filled,stuffed
filled_cabbage,stuffed_cabbage
filled_food,stuffed_food
filled_leaf,dolma
filled_vegetable,stuffed_vegetable
filling,fill,fullness
film
finally,at_last
financial_support
find-(to)
fine_(penalty)
finger
finger_spelling,finger_alphabet
fingernail,nail
fingerprint
fingerspell-(to)
finish,complete-(to)
finished,complete,completed,all_done,done_(finished)
fire
fire_extinguisher
fire_place,campfire_site
fire_truck,fire_engine
firecraft
firefighter,fireman
fireplace
firework
first,primary
first_aid
first_aid_kit
fish-(to)
fish_(animal)
fish_(dried)
fish_(food)
fish_(frozen)
fish_bone
fish_cage
fish_finger
fish_skin
fishball
fishburger
fisherman
fishing
fishing_(sport)
fishing_line
fishing_rod
fishnet
fist
five_(digit),5
five_(index_number)
fix,mend,repair-(to)
fixing,fix,mending,mend,repair,reparation
fjord
flag
flame
flashlight,lantern
flat
flatfish
flavouring,condiment,seasoning
flavouring,seasoning_(liquid)
flavouring,seasoning_(powder)
flax
flea
fledgeling
flight_attendant
flight_deck,cockpit
flight_instrument(s)
float-(to)
floating,afloat
floating_container
flood
floor,storey,level,etage
floor
floor_(42nd)
floor_(first)
floor_covering,linoleum
florist
flour
flower,bloom,blossom
flower
flower_(dried)
flower_(from_bulb)
flower_(protected)
flower_fairy
flower_meadow
flu,influenza
flute,recorder
flute,transverse_flute
flute_(alto)
flute_(soprano)
fly,flying_insect
fly-(to)
flyer
flying
foal
foam,mousse
fog
fold,folding,pleating
fold,pleat-(to)
folder
folder_(digital)
folk_music
folk_tale,legend
follow-(to)
follow-(to)_(OLD)
food
food_(frozen)
food_ball
food_processor,kitchen_machine
foot
football,soccer_(activity)
football,soccer_(sport)
football_rule(s)
football_supporters_club
football_team
footprint
for_(in_exchange_for),instead
for_(the_purpose_of),in_order_to
forced,compelled,obliged
forefather
forehead
foreign
foremother
foreskin
forest,bush,wood,woods
forget-(to)
forgetting,amnesia
forgive,pardon-(to)
forgiven
forgiveness,pardon
fork
fort,fortress
forward
fossil_fuel,coal_(etc)
foster_home
foster_mother
foster_parent
foundation,base,fundament
foundation_(building)
fountain
four-leaf_clover
four_(digit),4
four_(index_number)
four_o'clock_eating_break
fox,jackal,coyote
free,freely
free_of_charge,gratis,for_free
freedom,liberty
freestyle_skiing
freeze,solidify-(to)
freezer
freezing,hardening,solidifying
freighter
frequency
frequency_(wave_motion)
fresh
fresh_cheese
fried
friend
frog,toad
from
from_sky
front,front_of_a_thing
fruit
fruit_(dried)
fruit_(pointed)
fruit_cream,compote
fruit_juice,juice
fruit_salad
fruit_yogurt,fruit_yoghurt
frustrated
frustrating
frustration
fry,saute-(to)
frying_pan
fuel
fuel_gauge
full,satisfied
full
function-(to)
function
functional
fundamental,basic
fundamental_law
fundamental_rule
fundamentalism
fundamentalism_(religious)
fundamentalist
fundamentalist_(religious)
funeral
funeral_(religious)
funnel
funny,humorous
fur,coat_(animal),hair_(animal)
furniture
furred_animal
fuse
fuselage
future
future_(uncertain)
future_tense
g_(lowercase)
galaxy
gale
galley_(boat)
gallop-(to)
gallop
gamble-(to)
gamble
gambler
game
game_box
game_rule(s)
garage
garbage_can,rubbish_bin,trash_can
garden
garden_centre
gardener
garlic
gas
gas_(fuel)
gas_(fuel_from_biomass)
gas_cylinder
gas_planet
gasoline,gas,petrol
gastrointestinal_system
gather,assemble-(to)
gathering,assembly,meeting,conference
gathering_of_scouts,jamboree
gauge,gage,meter
gelding
gender,sex
gene
general
general_practitioner
generalization
genetics
genitals,sex_organs
genitals,sex_organs_(female)
genitals,sex_organs_(male)
genocide,holocaust
geographer
geography
geography_(class)
geologist
geology
geology_(class)
geothermal_energy
gerbil,guinea_pig,hamster
germination
get,acquire,receive-(to)
get_engaged-(to)
geyser
ghost,phantom
ghost_(OLD)
giant
giant_(human)
gift,offering,present
gift_shop
gigantic
gill
ginger
ginger_(powder)
ginger_sauce
giraffe
girl
girlfriend
girth,cinch
give,offer,provide-(to)
give_artificial_respiration,resuscitate,revive-(to)
give_birth-(to)
giving,gift
glacier
gland
glass,drinking_glass
glass_craft
glass_jar
glass_material
glasses,eyeglasses
glassware
glider
glitter
globe_(map)
glove(s),mitt(s),mitten(s)
glow-(to)
glow
glue,adhesive,paste
glue,paste,stick-(to)
gluten-free
go,depart,leave-(to)
go-kart,kart
go_ashore-(to)
go_by_airplane,fly-(to)
go_by_car-(to)
go_by_horse-(to)
go_to_sea-(to)
goal
goat
goblet,wineglass
goblin
gold
goldfish,guppy,pet_fish
goldsmith
golf_(activity)
golf_(sport)
gong
good,well,fine,ok,okay,all_right
good_conscience
goodbye,farewell
goodness
goods,contents
goose_(bird)
goose_(food)
gopher,ground_hog
gospel
govern,rule-(to)
government
government_(OLD)
grace,grace_of_God
grain,cereal
grammar_(general)
grandchild
grandfather,granddad,grandpa
grandfather_(maternal)
grandfather_(paternal)
grandmother,grandma,granny
grandmother_(maternal)
grandmother_(paternal)
grandparent
grape,grapes
grape_juice
grapefruit
grapheme
grass
grasshopper
grater,grinder
grave
grave_field
gravity,gravitation
gray,grey
graze-(to)
great,wonderful,fantastic
great_experience
greater_than_(relation)
green_(bci)
green_(ckb)
green_onion,scallion,spring_onion
greengrocer
greenhouse,glasshouse,hothouse
greeting,shalom,salam_(etc)
grid,matrix
grocery_store,food_store,supermarket
grocery_store,food_store,supermarket_(OLD)
groin
groom_(horse)-(to)
groom_(horse)
group_(people)
group_of,much_of,many_of,quantity_of
grove
grow-(to)
growl_(dog)-(to)
growth,growing
grunt_(pig)-(to)
guard_duty
guess,estimate-(to)
guess,estimation
guest_room
guilt
guilty
guitar,string_instrument
gull,seagull,sea_gull
gun,firearm
gutter,eaves_trough
gym,gymnasium
gym,gymnasium_(OLD)
gym_mat
gym_mat_(OLD)
gymnastics
gynecologist
h_(lowercase)
habit,custom
habitation,dwelling_place,site
hail
hair
hair_(head)
hair_accessory
hair_drier,blow_dryer
hair_pin,bobby_pin
hair_spray
hair_tie
half,one-half
half_an_hour
hall
halva,halvah,halwa
hamburger
hamburger_(OLD)
hamentasch
hammer,gavel,mallet
hammer_throw
hammock
hand
hand_splint
handbag,shopping_bag,carrier_bag
handball_(activity)
handball_(sport)
handcraft,craft-(to)
handcycle
handgun,pistol
handicraft_shop
handkerchief
handle,switch
handmade_figure,handicraft_(animal)
handmade_figure,handicraft_(person)
handmade_object,handicraft
handwriting,penmanship_(class)
hang,hook-(to)
hang_gliding
hangar
happen,occur-(to)
happiness,fun,joy,pleasure
happy,glad,gladly,happily
harassment
harbour
hard,firm
hard_(OLD)
hard_cheese
hard_rock
hare
harmony,harmoniousness,concord,concordance
harness-(to)
harness
harness_(horse)-(to)
harness_(horse)
harp
harpsichord
harvest
hat,cap,hood
hate,hatred
hate-(to)
hate-(to)_(OLD)
have-(to)
have_a_tea_break,have_a_coffee_break-(to)
have_a_view,have_an_opinion-(to)
have_impact_on-(to)
hawk,eagle_(OLD)
hay
he,him,himself
he,she,him,her,one
head
head_lamp
head_louse
head_with_hair
headmouse
headscarf
headset
heal-(to)
health
health_goods_shop
healthy,well
heap_of_sand
hear,listen-(to)
hearing,audition,auditory_sense
hearing-impaired
hearing-impaired_(OLD)
hearing_aid
hearing_impairment
heart
heart_attack
heart_disease
heat-(to)
heat
heavy
hedgehog
hedgehog_(OLD)
heel
heel_(shoe)
height,altitude
height,tallness
helicopter
hell
hello,greetings
helmet
helmet_(OLD)
help,aid,assist,serve,support-(to)
help,aid,assistance,support
helper,aide,assistant,personal_assistant
helpful,assistive,supportive
hen
henhouse,chicken_coop
her,hers
herb,spice_plant
herb_flavouring
herb_flavouring_(powder)
herb_sauce
herbivore
here
hero
heroic
herring,sardine
heterosexual
heterosexuality
hibernation
hiccup(s)_(1)
hiccup(s)_(2)
hidden_thing
hidden_treasure,treasure_trove
hide,conceal-(to)
hide,conceal_(secret)-(to)
hide_and_seek
hiding_place,cache
hierarchy
high,tall
high_heeled_shoes,high_heels
high_jump
high_tide
high_water
hijack,make_a_coup-(to)
hijacker,coup_maker
hike-(to)
hiking
hill
hip
hippopotamus
his,her,hers,one's
his
hiss_(cat)-(to)
historian
history
history_(class)
history_teacher
hit-(to)
hitch,tie_up,fix_up-(to)
hitchrack,hitching_bar
hobbit
hobby,pastime
hockey_helmet
hoist,lift
hold,contain_(1)-(to)
hold,contain_(2)-(to)
hold_(with_hand)-(to)
holding
hole
holiday,festival
holiness
holy
holy_book
holy_event
home
home_run
home_worker
homeward
homework,home_studying
homosexual
homosexual_(female),lesbian
homosexual_(male),gay
homosexuality
homosexuality_(female),lesbianism
homosexuality_(male)
honest,honestly
honesty
honey_(food)
honey_(spread)
hoof
hoof_pick
hook,hanger
hop-(to)
hope-(to)
hope
hopeful
horizon
horizontal-(a)
horizontal
horn(s),antler(s)
horn(s)
horse
horse_box,stall
horse_brush,body_brush
horse_cloth
horse_droppings
horse_neck
horse_racing
horse_rider,equestrian
horse_rump
horse_sled,horse-drawn_sleigh
horse_sled_sport
horse_trailer,horsebox
horsehair
horseradish
horseshoe
horseshoe_nail
hospital,clinic
hostage_(1)
hostage_(2)
hot,spicy,peppery
hot_(temperature)
hot_dog,frankfurter
hot_spring
hot_tray,chafing_dish
hotel,motel
hour,o'clock
house,building,dwelling,residence
house_work,housekeeping,housework
houseboat
housekeep,housework-(to)
housekeeper
hovercraft
how-(question)
how
how_much,how_many
hug,cuddle,embrace-(to)
hug,squeeze,embrace
huge
hull,body
hum-(to)
human_rights
humble,meek
humerus,upper_arm_bone
humid,damp,moist
humidity
hummus
hungry
hunt,hunting
hunt-(to)
hunter
hurdles
hurricane
hurry,rush-(to)
hurry,rush
hurry_(in_a),hurried,rushed
hurt,pain_(feel),suffer-(to)
husband
hydropower,hydro_energy
hydrotherapist
hydrotherapy
hyena
hygiene
hygiene_(personal)
hymn,psalm,gospel_song
hymnal,hymn_book
hypodermic_needle
hypodermic_needlepoint
hypothesis,theory
hysterectomy
i_(lowercase)
ice
ice_coated,ice_covered
ice_covering,ice_crust,ice_coating
ice_cream,sherbet,sorbet
ice_cream_(OLD)
ice_cream_(bar)
ice_cream_(cone)
ice_cream_(lollipop)
ice_field
ice_hockey_(activity)
ice_hockey_(sport)
ice_layer
ice_skates
ice_skating_rink_(indoor)
iceberg
icing
icy,frozen
idea,thought
identity_card
if
illegal,criminal
illness,disease,sickness_(sick_person)
illustrate-(to)
illustrated,illustrating
illustration
immoral,bad,wrong,morally_wrong
immune_(medical)
immunity_(medical)
impact
impermeable_material,insulation_(material)
import-(to)
import
import_(computer)-(to)
importance,significance
important,significant
imported
impoverish-(to)
imprint,depression
imprint,trace,track
improve-(to)
improve-(to)_(OLD)
improvement,enhancement
improvement_(OLD)
in,inside,interior,internal
in_love
incense
incest
include-(to)
incorrect,bad,inaccurate,wrong
incorrect_thinking
increase,enlarge-(to)
indefinite
independent
independent_living
index,list_of_contents_(in_a_book_etc)
indicator_(action)
indicator_(active)
indicator_(adverb)
indicator_(conditional)
indicator_(definite_form)
indicator_(description)
indicator_(description_after_fact)
indicator_(description_before_fact)
indicator_(future_action)
indicator_(future_conditional)
indicator_(future_passive)
indicator_(future_passive_conditional)
indicator_(imperative_form)
indicator_(passive)
indicator_(past_action)
indicator_(past_conditional)
indicator_(past_participle_1)
indicator_(past_participle_2)
indicator_(past_passive)
indicator_(past_passive_conditional)
indicator_(plural)
indicator_(present_action)
indicator_(present_participle)
indicator_(present_passive_conditional)
indicator_(thing)
indicator_(things)
indigestion,heartburn
indigo
indoor,indoors
indoor_(character)
industry
inequality
infect-(to)
infected
infection
infectious,contagious
infertile,sterile
infinite,limitless
infinite,limitless_(OLD)
infiniteness,boundlessness,limitlessness
infiniteness,boundlessness,limitlessness_(OLD)
infix
inflammable,flammable
inflatable
inflate-(to)
inflation
influence,affect-(to)
influence
influenced,affected
information
ingredient
inhaler
injection,inoculation,shot
injure,hurt-(to)
inlet
innocence
innocent,not_guilty
insect,bug
insect_(pest)
insight
insomnia
inspiration
inspire-(to)
inspired
instruction(s),direction(s)
instruction,teaching
insulin
insurance
intellectual_impairment,cognitive_impairment,mental_impairment
intensity
interdental_brush,interdental_rager
interest
interesting,interested
interjection
international
internet_(1)
internet_(2)
interrogate-(to)
interrogation
interrupt_(in_conversation)-(to)
interruption_(in_conversation)
intersection,crossroad
interview-(to)
interview
interviewer
intestine(s),bowel(s),gut(s)
intimacy,closeness
intimate,close
into
into_(backward)
into_(downward)
into_(upward)
intranet_(1)
intranet_(2)
intrauterine_device,IUD
introduce,present-(to)
intuition
invent-(to)
invertebrate
invisible
invitation_(general_spoken)
invitation_(general_written)
invitation_(spoken)
invitation_(written)
invoice
iris_(eye)
iron,smoothing_iron
iron-(to)
iron
iron_age
ironing_board
island
isosceles_triangle
it,itself
itch
its
j_(lowercase)
jackfruit
jaguar
jam,jelly,marmalade,preserves
janitor,caretaker
javelin,spear
javelin_throw
jealous
jellyfish
jet,jet_plane
jet_ski,water_scooter
jewel,gem,gemstone
jewelry,jewellery
jigsaw_puzzle
jobcentre,job-centre
jockey
joint
joke-(to)_(general)
joke_(general)
joke_(spoken)-(to)
joke_(spoken)
journalist
joystick
judge-(to)
judge
judgement,law_(in_combinations)
judo
juicy
jump-(to)
jump
jump_(backward)
jump_rope,skipping_rope
juridical
jury
just,fair
justice
justification
justified
justify-(to)
k_(lowercase)
kangaroo,wallaby
karate
kart_racing,karting,go-karting
kayak
kazoo
kebab_(Middle_East)
kebab_(Scandinavia)
kebab_(UK,NL)
keel
keep,preserve,save-(to)
kernel,particle
ketchup
key,tonality
key
key_(computer)
key_guard
keyboard
keyboard_(computer)
keyboard_(expanded)
keyboard_(mini)
kibbutz
kick-(to)
kiddush,blessing_over_wine
kidnap-(to)
kidnapper
kidney
kill,murder-(to)
killer,murderer
killing,murder,slaughter
kind,kindly
kindergarten,preschool,nursery,play_group
king
kiosk,booth,stall
kiss-(to)
kiss
kitchen
kitchen_tongs
kitchen_tool,utensil
kite
kite_flying
kitten
kitten_(OLD)
knee
knee_pad
kneel-(to)
kneeling_(kneeling_person)
knife,sword
knight
knit-(to)
knitting_needle(s)
knock,tap-(to)
knock,tap_(sound)
knocking
knot
know-(to)
knowledge,class_(in_combinations)
koala
kyphosis,scoliosis
l_(lowercase)
labour
labyrinth,maze
lacrosse_(sport)
lacrosse_(sport)_(OLD)
ladder
ladle
ladybird
lake,pond
lamb,mutton
lamb-(to)
lamb
land_(airplane)-(to)
land_(rocket)-(to)
landing,airplane_landing
landing_(rocket)
landing_gear
landscape_design
landscape_designer
language
language_(class)
language_development
laptop
large_intestine
larynx
lasagne,lasagna
last,final
last_(person,etc)
last_month
last_night
last_week
last_year
late
laugh,laughter
laugh-(to)
laundromat,launderette,laundry
laundry_(workplace)
lava,magma
law,The_Law
law-(a)
law
lawn,meadow
lawn_bowling,bowls_(sport)
lawn_mower,mower
lawyer
lawyer_(for_the_defence)
lay_the_table-(to)
layer,level
lead,direct,guide-(to)
lead
leader,director,guide_(1)
leader,director,guide_(2)
leadership,guidance
leaf,flap
leaf
learn-(to)
learning_difficulty
leather
lecture-(to)
lecture
lee,shelter
leek
left
left_turn,left_(position_or_direction)
leftovers,left_overs,food_waste_(food_thrown_away)
leftovers,left_overs_(food_used_again)
leg
leg_and_foot
legal
legal_aid
legal_person_(in_combinations)
legs_and_feet
leisure_time
lemon
lemonade
lend,loan-(to)
length,longness
leopard
leprechaun
less_than_(relation)
lesson,lecture,class
let,allow,permit-(to)
let_fall,drop-(to)
let_us,let's
letter,mail,post
letter_carrier,postman,mailman
lettuce,leafy_vegetable
liberation
librarian
library_(building)
library_(room)
lichen
lick-(to)
lid
lie-(to)
lie-(to)_(OLD)
lie
lie_(OLD)
lie_down,lie-(to)
life-jacket
life
lifeboat
lifeline
lifetime,life-time,lifespan
lift,raise-(to)
light
light_(not_dark)
light_(weight)
light_meter
light_switch
light_year
lighthouse
lightning
like-(to)
lime
limit(s),limitation,restriction
limit(s),limitation_(OLD)
limit,restrict,restrain,confine-(to)
limited,restricted,confined
limited_time,interval,period,awhile,for_a_while
line,queue
line,stripe
linear,straight
linear_thing
linear_thing_(horizontal),bar
linen,flax_fabric
linguist
linguistics
lion
lip(s)
lipstick
liquid
liquor_shop,liquor_store
list,inventory
literature
little,small
little_person
littleness,smallness
live,dwell,reside-(to)
live_(life)-(to)
liver
living_room,lounge,sitting_room,front_room,parlor,parlour,waiting_room
lizard,reptile_(snake_like_animal)
load
lobster
lock-(to)
lock
lollipop,sucker
lonely,lonesome
long
long_for,yearn-(to)
long_jump_(OLD)
long_jump_(sport)
long_time
longer
longest
longing,yearning
longsighted,farsighted,presbyopic,hyperopic
longsightedness,farsightedness,presbyopia,hyperopia
lose_(fail_to_keep)-(to)
lose_(fail_to_win)-(to)
lose_(fail_to_win)-(to)_(OLD)
loss_(competition)
loss_(emotional)
lottery,game_of_chance
lotto,bingo_(etc)
loud,noisy
loudspeaker
louse,stinging_insect
lovable
love,affection
love-(to)
low,short
low_tide,ebb
low_water
lower-(to)
lower_arm
lower_arm_bone(s)
lower_body
lower_leg,shank,shin
lowness,shortness_(height)
luck,fortune
lucky,fortunate
lukewarm,handwarm,tepid
lulav
lullaby
lumberjack
lump(s)
lumpy
lunar_eclipse
lunch,dinner
lunch_box
lung(s)
lymph
lymph_node,lymph_gland
lymphatic_system
lynx,bobcat
m_(lowercase)
macaroni
machine,appliance,engine,motor
magazine,journal
magic
magical
magician
magnet
magnetic_field
magnetic_pole
magnetism
magnifier,magnifying_glass
mail,post-(to)
mailbox,letterbox,postbox
main_dish,main_course
make,manufacture,produce-(to)
make-believe,pretend,imaginary
make-believe_man
make-believe_person,imaginary_person
make-believe_person_(in_forest)
make-believe_person_(in_water),water_nymph
make-believe_person_(under_ground)
make-believe_woman
make_a_speech-(to)
make_and_tend_a_fire-(to)
make_cheese-(to)
make_compost-(to)
make_sign_of_the_cross-(to)
make_the_bed-(to)
maker,manufacturer,producer
makeup
making,production,fashioning
male,masculine_(person)
male_friend
male_genitals_(man_with_penis)
malodor,malodour,stench
mammal
mammoth
man,male
man-made,produced
man-made_item,artefact,artifact,product
man_doll_(e.g._Ken)
manager,secretary
mandolin
mane_(horse)
mane_(lion_etc)
mango
manhole_cover
manna
manure,fertilizer
map
map_reading
maple-leaf
maple_syrup
maple_syrup_flavouring
maracas,calabash_(etc)
mare
margarine
market
marriage,wedding
marriage
marriage_(religious)
married_(to_be)
marry-(to)
marshmallow
marsupial_(animal),pouched_mammal
martial_arts
mash,crush,squeeze,squash_(food)-(to)
mash,mush,pulp_(food)
mask,false_face
mask_(disguise)
massage-(to)
massage
masseur
mast
masturbation
match
matching_game
material,raw_material,stuff
math,mathematics_(class)_(1)
math,mathematics_(class)_(2)
mathematical_difficulty
mathematician_(academic)
mathematics,arithmetic,math_(1)
mathematics,arithmetic,math_(2)
maturation
matzo
mausoleum
maybe,perhaps,possibly
meal
mean,cruel
mean,signify-(to)
meaning,sense,significance
measure-(to)
measurement,measure
measuring_cup
measuring_spoon
meat
meat_(diced),diced_meat,chunks_of_meat
meat_(dried),dried_meat
meat_(frozen),frozen_meat
meat_(minced),minced_meat,ground_meat
meat_sauce
meatball
mechanic,technician
mechanical_engineer
media_player
medical,medically
medical_aid
medical_examination
medical_insurance
medical_treatment,medical_care
medical_tube,catheter,cannula
medication_for_breathing
medicine,medical_practice
medicine,medication
meditate-(to)
meet,encounter,see-(to)
meeting,assembly,conference
meeting,encounter
meeting_and_parting
meeting_room,auditorium
melodica,blow-organ
melon
member
membrane,drumhead,drum_skin
memo,reminder_note
memory
memory_game,Kim's_game
memory_stick,USB-memory
menopause
menorah
menstrual_blood
menstruation,menstrual_period,period
mental,intellectual,rational,thinking
mental_illness
mercury
mermaid
merry-go-round,carousel
message,content_(communication)
message
metal
metal_(music)
metal_bar
metal_craft
metaphor
metaphor_(winged)
meteorologist
meteorology
mew,meow-(to)
mezuzah
micro-organism
microphone
microscope
microwave-(to)
microwave_oven
middle,centre
midnight
midnight_sun
midsummer
military,armed_forces,armed_services
military_plane
military_reserve_duty
milk
milkmaid,dairymaid
milkman
milkshake
milkshake_(OLD)
millepede
mind,intellect,reason
mind_sports
mine
minister,pastor,preacher,priest,rabbi
minister_(government)
mink
minus,no,without
minute
minutes
miracle
mirror
miscarriage,abortion_(general)
miscarriage,abortion_(spontaneous)
misericordia_(forgiveness_from_God)
mislead-(to)
miss,lose-(to)
missal,liturgical_book
missionary
mistake,error,fault
misuse-(to)
misuse
mite,tick
mix,blend-(to)
mixer,blender
mixing_spoon
mixture
mobile_phone,cellphone
modem
modern
molasses,dark_syrup,black_treacle
molecule
mollusk(s),mollusc(s)
monarchy
money,cash
money_on_a_regular_basis
monkey,ape,gorilla,primate
monotheism
monster
month
monument,commemorative_work
moo,bellow-(to)
mood
moon
moon_axis
moon_phase,phase_of_the_moon
moose,elk
moral,good,right,morally_right
more
morning_(before_noon)
morning_(early)
morpheme
morphology
mortal
moshav
mosquito,gadfly,horsefly,cleg
moss
most,maximum
mother's_milk
mother,mom,mommy,mum
mother-in-law_(partner's_mother)
motivate-(to)
motivated
motivation
motor_sports
motorboat
motorboat_sport
motorcycle,scooter
motorcycle_racing
motorcycling,motocross
mountain
mountain_berry,cowberry,lingonberry
mountain_bike
mountain_biking
mountain_climbing
mountain_pasture
mountain_range
mountain_sports
mountains_with_valley
mourn-(to)
mourning,grief
mouse,pointing_device
mouse
moustache
mouth
mouth_(wide-open),open_mouth,gape
move,movement
move-(to)
move_(change_position)-(to)
move_bowels,defecate,stool,shit,ca-ca-(to)
movement,motion_(1)
movement,motion_(2)
movie,action_film,action_movie,film_(action)
movie,film
movie,romance_movie,romance_film,film_(romantic)
movie_theatre,cinema
much,many,very
mud,clay
muffin,bun_(sweet)
mug,cup
multi-sport_event
multi_storey_building
multi_storey_home
multiplication
multiply-(to)
multitude
mummy_(general)
mummy_(imaginary)
murder-(to)
murder
murderer
muscle
muscle_(OLD)
museum
mushroom
music
music_therapist
musical
musical_group
musical_instrument
musical_instrument_(in_combinations)
musical_instrument_(with_many_strings)
musical_note,music_(in_combinations)
musician
muskrat
must,have_to,be_forced_to-(to)
must_(a)
mustard
mustard_(powder)
mustard_sauce
mustelid_(animal)
muzzle
my,mine-(feminine)
my,mine-(masculine)
my,mine
mysterious,unknown
mystery,unknown
myth
n_(lowercase)
nag-(to)
nail
nail_polish,nail_varnish
name,label,term,title
naming_ceremony
naming_ceremony_(religious)
napkin,serviette
narrow
nasal_cavity
nation
national
national_day
national_park
nature_craft
naughty,not_nice
naughty
navel
navigate-(to)_(general)
navigate_airplane-(to)
navigation_(general)
navigational_sign
navy
near,almost,close,nearly
nearness,closeness,proximity
nearsighted,shortsighted,myopic
nearsightedness,shortsightedness,myopia
necessary,necessarily,needed
neck_(body)
neck_(head)
necklace
need,require-(to)
need_(needy_person)
needle
negative_dependency
neigh,whinny-(to)
neighbour
neither
nephew
nerve
nervous_system
net
neurological
neurologist
neuron
never
never_(OLD)
new
newness,novelty
news
newspaper,bulletin,newsletter
next
next_month
next_week
next_year
nice,pleasant
niece
niece_or_nephew
night
nine_(digit),9
nine_(index_number)
nipple(s)
no-(exclamatory)
no_one,nobody
no_speech,anarthria
nocturnal_emission,wet_dream
noise_(loud)
noisemaker,musical_toy
non-alcoholic
none,nothing_(OLD)
nonsense-(exclamatory)
nonsense
nonspeaking
noon
nor
north
northeast
northern
northward
northwest
nose
nosy
not,negative,no,don't,doesn't
notary
notary_(lawyer)
notebook,writing_book
nothing,none
noun
now
nowhere,no_place
nuclear_energy
nuclear_fallout,radioactive_dust
nuclear_fuel
nuclear_radiation,radioactivity
nucleus_(atom)
nude,naked
nudity
number,numeral
number
nurse
nut
nutcracker
nutrient,nutrition
o_(lowercase)
oats
obedience
obey,comply-(to)
oboe_(1)
oboe_(2)
observation
observe-(to)
occupational_therapist
occupational_therapy
occupational_therapy_room
ocean,sea
octopus
odd_number
odometer
odometer_(OLD)
oere_(currency)
oesophagus,gullet
offer,sacrifice-(to)
office
offspring,child
often,frequent,frequently
oil,lubricant
oil_(fuel)
oil_gauge
oil_lamp
oil_power,oil_energy
oil_tanker
okra,lady's_finger
old,elderly
old-age_pension
old
old_(opposite_new)
olive
omelette,omelet
omnivore
on
once
once_upon_a_time
one_(digit),1
one_(index_number)
one_storey_building,bungalow
one_storey_home
one_third
onion,vegetable_(bulb)
online_game,multiplayer_game,network_game
open-(to)
open
open_one's_mouth,hold_one's_mouth_open,gape-(to)
opener
opening
opera
operation
ophthalmologist,oculist
opinion
opossum,possum
opposing_forces,counter-forces
opposite_meaning,opposite_of,opposite
opposition,counter_purpose
oppressed,unfree
oppression,captivity,slavery
optician
or
oral_cavity
oral_sex
orange,citrus_fruit
orange_(bci)
orange_(ckb)
orbit_of_the_moon
orchard
organ,inner_organ,inner_body_part
organ,pipe_organ
organ_(body)_(OLD)
organism
organization,organizing
organize,arrange-(to)
orgasm
orienteer,read_map-(to)
orienteer_(sport)-(to)
orienteering_(sport)
orthopaedist
orthoptist
osteopath
ostrich
other,another_(person)
other,another_(thing)
others_(persons)
otolaryngologist
our,ours-(feminine)
our,ours-(masculine)
our,ours
out,exterior,external,outside
out_of,exit_(downward)
out_of,exit_(forward)
out_of_(backward)
out_of_(upward)
out_of_body_(downwards),excretion
out_of_body_(upward),regurgitation
outcome,result
outdoor,outdoors
outdoor_(character)
outing,excursion
oval,ellipse_(shape)
oval,elliptic,elliptical
oval
ovary
oven_paper
oven_tray
over,above,superior
overlay
overlay_keyboard,membrane_keyboard
overspend,buy_over_budget-(to)
overturn,turn_over,tip_over-(to)
owl,night_bird
own,possess-(to)
ownership,possession
ox
oyster,clam,mussel
p_(lowercase)
pacifier,dummy
paddle,oar
paddle_(two_blades)
paddle_boat,pedal_boat,water_bike,pedalo
paddock
paediatrician
pail,bucket
pain,suffering
painful,painfully,sore
paint,dye-(to)
paint,dye
painter
pair
palate,roof_of_mouth
palm
palmtop,PDA
pancake,crepe,tortilla
pancreas
pandemic
panpipe
pants,jeans,slacks,trousers
paper,card,page
paper_clip
paper_craft
paper_money,bill
parachute
parachute_harness
parachuting
parakeet,budgie
parallel
paralysis,palsy
parasailing
paraskiing
paratrooper
parcel,package
pardon,what_did_you_say
parent
park-(to)
park
parking_lot
parking_permit
parking_ticket
parrot,myna,talking_bird
parsnip
part,bit,piece,portion,part_of
part_of_speech
participant
participate-(to)
participation,involvement
participation
parting
partner_(game,dancing,business)
party,festival
passenger
passive
passivity
passport
past
past_tense
pasta
pasta_salad
pasta_wheel
pasture,enclosed_field
pasture,put_out_to_pasture-(to)
pasture
pate,crown_(body_part)
paten,holy_tray
patience
patient,enduring
patient_(in_medical_care)
pavement,sidewalk
paw
pay,spend-(to)
pay_channel
peace,peace_of_mind,serenity
peace_(opposite_war)
peaceful,serene,calm
peach,nectarine
peacock
peanut
peanut_butter
pear
peas
peel-(to)
peel
peer
pelican
pen,pencil
pencil_case,pencil_box
penetrate,go_through-(to)
penguin
penis
pennywhistle,tin_whistle
pensioner
people,tribe,clan,folk
people_in_the_north_(Lapps,Eskimos)
pepper_(powder)
pepper_(seasoning)
pepper_(vegetable)
pepper_sauce
percent,percentage,%
perch_(fish)
percussion_instrument
perfect
perfection
perform-(to)
performance,show
perfume,fragrance,aroma,scent
period,point,full_stop,decimal_point
period_(wave_motion)
period_of_life
permeable_material
permission,allowance
permission,allowance_(moral)
perpendicular
perseverance
persevere-(to)
person,human_being,individual,human
personal_measurement
personality
persuade,convince-(to)
persuasion
pet
pharmacist
philosopher
philosopher_(academic)
philosophy
philosophy_(class)
phoneme
phonology
photograph,photo,pic
physical_impairment,physical_disability
physicist
physics
physics_(class)
physiotherapist
physiotherapy
physiotherapy_room
piano_(1)
piano_(2)
piccolo_(1)
piccolo_(2)
pick-(to)
pickled
picnic
picture,image,icon,painting
pie,tart
pier
pier_(OLD)
pierce-(to)
pierce_(jewellery)-(to)
piercing_(thing)
pig
pig_(wild),boar_(wild)
piggery
piglet
pill,tablet
pill_box
pillow,cushion
pillowcase
pilot
pilot_boat
pimple,blemish
pin
pinch,pincer_grip
pinch,pluck,tweeze-(to)
pineapple
pink_(bci)
pink_(ckb)
pipe,hose,tube_(1)
pipe,hose,tube_(2)
pipe,smoking_pipe
pipe,tube_(closed)
pirate
pit,stone-(to)
pit,stone
pita
pitch_(sound)
pitcher,jug,kettle,pot
pizza
pizza_slice(s),sector(s),circle_sector(s)
pizzeria
place,area,location,space
place_to_feed,feeding_place,feeding_ground
placenta
placenta_(OLD)
plague
plan,design,method,system
plan,design-(to)
planet
plant-book,dictionary_of_plants
plant-louse
plant
plant_(edible)
plaster_cast,cast_(medical)
plastic
plastic_bag
plastic_wrap
platform,stage
play,game_(in_combinations)
play,recreation
play-(to)
play_(instrument)-(to)
play_(theater)
play_football-(to)
playground
playhouse,play_house
playroom,family_room,recreation_room
please
pliers,tongs,tweezer(s),pincer(s)_(pair_of)
plough
plough_(ancient),ard,ard_plough,scratch_plough
plug
plug_in,connect_(digital)-(to)
plug_in,connect_(power)-(to)
plum,drupe
plural
plus_minus
plus_sign_(low)
pocket
pod,seedcase,seedpod
podiatrist,chiropodist
poem
poetry
point,indicate-(to)
point,tip,peak
point_of_view
pointer,arrowhead
pointer,arrowhead_(small)
pointer
pointing
poison
polar_bear
polar_night
polder_(Dutch)
pole
pole_vaulting
polenta
police_force,police
police_officer,policeman,policewoman
polish-(to)
polisher
politician
politics
pollen
pollution
polo
polytheism
pool,snooker
pool
poor_(little_money)
poor_(without_possessions)
pop_music
popcorn
popsicle
porcupine
porcupine_(OLD)
pork,ham
porridge
port_(boat)
port_(device)
portability
portable
position
positive
possibility
possible
post_office
post_position
postcard
pot,kettle,boiler
pot,pan
pot_stand,trivet
potato
potato_chip(s),chip(s),crisp(s)
potato_chips,crisps_(OLD)
potholder,oven_mitt
potty,chamber_pot,bedpan
pound_sterling
poverty
powder,dust
powdered_sugar,icing_sugar
power,powerfulness
power,powerfulness_(OLD)
power_(physics)
power_plant,power_station
powerful,mighty
powerful,mighty_(OLD)
practice,drill,exercise,rehearsal
practise,practice,drill,exercise,rehearse-(to)
pram_straps,safety_harness
prawn
pray-(to)
prayer
prayer_book,Siddur
preach-(to)
preceding,previous,former,earlier
preceding_(OLD)
precious,treasured
precious_thing,treasure
predict-(to)
prefix
pregnancy
pregnant
pregnant_(ckb)
premature_birth
preparation,readying,readiness,preparedness
prepare,set,set_up,ready,gear_up,fix-(to)
prepare_food,cook-(to)
preposition
prescription
present
present_tense
president
pressure
pressure_gauge
pretend,make_believe-(to)
price_rise
prime_minister
prince
princess
principal,headteacher
print-(to)
printer,typewriter
prison,jail
prison_officer
prisoner
private
privy,outhouse
prize,award,trophy
probable,likely,probably
problem
proclaim,announce-(to)
proclamation,announcement
proclamation_(written)
program,programme,presentation
program,programme
projectile,rocket,spacecraft
projector
promise,pledge-(to)
promise
promote-(to)
promotion
prone_board,scooter-board
pronoun
propeller,rotor_(blades)
prophecy
prophesy-(to)
prophet
prosecutor
prostitution
protect,cover,shelter,take_care_of-(to)
protected,saved
protected,sheltered
protected_water
protection,shelter
protection_of_the_environment
protection_with_pointer
protective_mask
protector,guard
protest,object,oppose-(to)
protest,objection,opposition
protest,resist-(to)
protest,resistance
protestantism
protractor
proud
province,county,region,state
prune
prune_(OLD)
psychiatrist
psychologist
psychologist_(OLD)
psychologist_(researcher)
psychologist_(researcher)_(OLD)
psychology
psychology_(OLD)
psychology_(class)
psychology_room
psychology_teacher
psychology_teacher_(OLD)
puberty
pubic_hair
public_(not_private)
public_(of_the_public)
public_(the_public)
public_room
public_transport
publication
publish-(to)
publisher
pudding,cream
puddle,pool,water_(ground_level)
pull,drag,tow,tug-(to)
pull,pulling
pump-(to)
pump
puncture,prick-(to)
punk_rock
pupil_(eye)
puppet
puppy
purple,violet_(bci)
purple,violet_(ckb)
purpose
purr_(cat)-(to)
purse,pocketbook,wallet
push,pushing
push,shove-(to)
pushboat
put,locate,place-(to)
pyjama(s),nightgown,nightie,pajama(s)
pyramid
q_(lowercase)
quality
quality_(measurement)
quantity_(measurement)
quarrel,row
quarter,one_quarter
quarter_of_an_hour
queen
question,be_sceptical,doubt-(to)
question
question_mark
quick,fast,quickly,rapid,rapidly
quickness,rapidity,speediness
quiet,quietly
quill(s),spine(s)
r_(lowercase)
rabbit,hare
rabies
raccoon
race,competition,contest
rack,single-foot-(to)
racket,racquet
radio_(1)
radio_(2)
radish
rag
rags_(worn-out_clothes)
railway_track
rain-(to)
rain
rain_gauge
rainbow
raincoat
raindrop
rainy
raise,grow,bring_up,cultivate-(to)
raise-(to)
raise_one's_hand,put_up_one's_hand-(to)
raised_wavy_line
raisin(s),currant(s)
raisins_(OLD)
rake
ram
ramp
rap_(music)
rape
rapids
rash_(skin)
raspberry,blackberry,compound_berry
rat,rodent,gnawer,gnawing_animal
rattle
rattle_(musical_instrument)
ravioli
raw,uncooked
reaching_aid,grabber
react-(to)
reaction
read-(to)
reading
reading_(class)
reading_difficulty
reading_lesson
ready,prepared
real,really
reality
realize,realise-(to)
rear,back_of_a_thing
receipt
receiver,dish
receiver
recent,recently
reception
recipe
reclaim_(marshes_etc)-(to)
reclining,lying_(person_lying_down)
record_(achievement)
recorder
recorder_(alto)
recorder_(bass)
recorder_(soprano)
recorder_(tenor)
recording_disk
recreation_room,moadan
rectangle,oblong_(shape)
rectangular,oblong
rectum
recumbent_bicycle
recycling_station
red_(bci)
red_(ckb)
redo-(to)
redo_(computer)-(to)
reed,bamboo_(tall_grass)
reed
reef-(to)
referee,judge_(sport)
referee_(football,soccer)
reflect,consider-(to)
reflection
reflection_(mental),consideration
reflector
reflexologist
refrigerator,fridge
refrigerator_(OLD)
regain,recover,retrieve-(to)
regret-(to)
rein
reindeer,caribou
relative,relation
relay
relay_(sport)
religion,naturalism
religion,naturalism_(OLD)
religion_(God_based)
religion_(class)
religion_(science_of),theology
religion_teacher
religious
religious_(God_based)
religious_(OLD)
religious_ceremony
religious_ceremony_(God_based)
religious_event
religious_fanatic
religious_fanatic_(God_based)
religious_gathering
religious_leader
religious_service
remember,recall-(to)
remember-(to)_(OLD)
remembrance_day
remote_control
rent,lease,hire,charter-(to)
rent,lease,let-(to)
rent
repair_room
repair_shop
repeat,copy,duplicate,reproduce-(to)
repetition,copying,duplication,replication
reproduction
republic
request-(to)
rescue-(to)
rescue
research-(to)
research
resent-(to)
resident
residential_institution,group_home,hostel,residential_home
resign,quit_(1)-(to)
resign,quit_(2)-(to)
resignation_(1)
resignation_(2)
resource_centre
respect,admiration
respirator
respiratory_illness
respiratory_system
responsibility
responsible
rest,comfort
rest-(to)
rest_period,break
restaurant,cafeteria
resurrection
retire-(to)
retired
retirement
retirement_pension
return,come_back,reverse-(to)
return
reuse,recycling
reuse,use_again,recycle-(to)
revelry,revel
rhinoceros
rhyme
rhythm_instrument
rhythm_method
rib(s)
ribbon,tape
rice
rice_flour
rice_noodle
rice_pudding,rice_porridge
rich,wealthy
rich_(taste)
rickshaw
ride,drive
ride-(to)
ride_(horse)-(to)
riding,horseback_riding
riding_boots
riding_clothes
riding_helmet
riding_instructor
riding_school,manege
rifle,shotgun
right(s)
right
right_triangle
right_turn,right_(position_or_direction)
rights_of_persons_with_disabilities,disability_rights
ring
ring_(finger)
rise,ascend,go_up-(to)
ritual
river,stream,current
road_(1)
road_(2)
road_and_car
road_sign,traffic_signal
roadrunner_(bird)
roar_(lion)-(to)
roast,joint_(of_meat)
rob-(to)
robber
robot
robot_doll
rock_(geology)
rock_music,rock'n'roll,rock
rock_planet,terrestrial_planet
rocket,spaceship
rocking_chair
rocking_horse
rocking_horse_(OLD)
roe_deer
roll,bun
roll-(to)
roller_skate-(to)
roller_skates
rolling_pin
roof,cover
room
root(s),rootage,root_system
root
rope,hawser
rose
rot,decompose-(to)
rot,decomposition,rotting_matter
rotate,circle,circulate,wind_up,orbit-(to)
rotation,circulation,orbit,lap,circle,round
roti,chapati,flatbread
rotisserie,spit
rotten,decomposed
rouge,blusher
rough_sea
round,circular
roundabout
router
row_house,attached_houses
rowdy,raucous
rowing
rowing_boat
royal
royal_family
rub,scrub-(to)
rubber_boat,dinghy
rudder
rug,carpet,mat
rugby,football_(N.A.)
rugby_ball,football_(N.A.)
ruin,wreck,wreckage_(building)_(1)
ruin,wreck,wreckage_(building)_(2)
ruin_(castle),castle_ruin
rule,regulation
ruler,measuring_stick,tapeline,tape_measure
run,jog-(to)
run,jog
runes
running
runway_(airport)
rye
s_(lowercase)
sack,bag
sack,dismiss-(to)
sacked,dismissed
sacking,dismissal
sacrament
sacrament_of_absolution
sacrament_of_anointment_of_sick
sacrament_of_baptism
sacrament_of_communion
sacrament_of_confirmation
sacrament_of_holy_orders
sacrament_of_marriage
sacrifice
sad,sadly,unhappily,unhappy
saddle
saddle_pad,saddle_blanket
sadness,sorrow,unhappiness
safari,wildlife_expedition
safe,safely,secure,securely
safety,security
sail
sail_(OLD)
sailboard,windsurf_board,windsurfing_board
sailboat,sailing_boat,yacht
sailboat_(OLD)
sailing
sailor
saint
salad
salad_dressing
sale
salesperson,shop_owner
saliva,spit
salivary_gland
salmon
salt
salt_(OLD)
salt_crystal
saltwater,seawater
salty
salty_(OLD)
salvation_(religious)
same,equal,equality
same_sound
samosa,pirogue
sanctify,consecrate-(to)
sanctity_of_life
sand
sand_play
sand_toy
sandal(s)
sandbox,sandpit,sandtray
sandstorm
sandwich
sandwich_(open_face)
sanitary_napkin,sanitary_towel,tampon
sap
sap_(flavouring)
sari
satellite
satellite_dish_(1)
satellite_dish_(2)
satellite_signal
satisfaction,contentment
sauce,gravy,relish,dressing
sauce,gravy,relish,dressing_(OLD)
saucepan
sauerkraut
sauna
sausage,frankfurter,hotdog,hot_dog
save_(computer)-(to)
save_as_(computer)-(to)
saw
saxophone_(1)
saxophone_(2)
say,speak,talk,tell,express-(to)
scabies
scale,measurement
scale_(weighing)
scalene_triangle
scales
scarf
scatter_ashes-(to)
scavenger,carrion_eater
scenery,landscape
sceptical,skeptical,questioning
scepticism,skepticism
schach
schedule,timetable
school
school_(in_combinations)
school_uniform
school_way
school_year
schoolbag
schoolmate
schooner
science,body_of_learning
science
science_centre
scientist,academic
scientist,researcher
scissors
scooter
scooter_(3_wheeled_electric)
score
scorpion
scoundrel,villain
scout_(etc)
scouting_(etc)
scrambled_eggs
scratch-(to)
scratch
screw
screwdriver
scrotum
sculpture
sea_anemone
sea_captain,skipper
sea_chart
sea_cucumber
sea_lion
sea_urchin
seal
seaplane
search-(to)
season
season_of_darkness
seat,sitting_(sitting_person)
seat_belt
seaweed
second_(ordinal)
second_(time)
secret
secret_agent,spy
secretary
see,look,watch-(to)
see_you_again
seed
seem-(to)
seesaw,teeter-totter,teeter_board
select_all,mark_all-(to)
self,oneself,ego_(person)
self-control
self-harm
self-harming
self-raising_flour
selfie
selfish,self-centred,self-centered,egoistic,egoistical,egocentric
selfishness,egoism
sell-(to)
semantics
semen
semi-detached_house
seminal_vesicle
send-(to)
senior_citizen
sense
sentence,clause,phrase
sentence,condemn-(to)
sequin(s),spangle(s)
server,host_(computer)
service_(help)
service_(work)
serving_spoon
set_square
seven_(digit),7
seven_(index_number)
several
sew-(to)
sewing_machine
sex_drive,sexual_urge,libido
sexual_abuse,sexual_assault,sexual_violence
sexual_activity
sexual_aid
sexual_arousal,sexual_excitement
sexual_harassment
sexual_intercourse,intercourse,copulation
sexual_play
sexual_pleasure
sexuality
sexually_mature
shadow,shade
shake,jiggle-(to)
shall,will-(modal_aux_v)
shallow
shallowness
shame
shampoo-(to)
shampoo
shamrock,clover
shape,form
share-(to)
shared_housing
shark
sharp_(knife)
sharp_(taste),acid,sour
shave-(to)
shave_(beard)-(to)
shaver,razor
shaving_soap,shaving_cream
she,her,herself
sheath
sheep
sheep_shed,sheep_barn
sheet(s),bedclothes,bed_linen
shekel
shekel_(character)
shelf
shell,crust
shellfish
shellfish_(without_claws)
shellfish_salad
shelter,refuge
sheltered_workshop
shepherd
shine,beam-(to)
shine-(to)
shine
shiny,glossy
shipping_forecast
shirt,blouse
shiva_(judaism)
shoal,school_(of_fish)
shoe
shofar
shoot-(to)
shooting_sports
shopping_centre,mall,plaza
shopping_centre_(OLD)
shopping_mall
short
short_message_system_(SMS),text_message
short_time_home
shortness_(distance,length)
shorts
shot_put
should,would-(modal_aux_v)
shoulder
shoulder_blade,scapula
shout-(to)
shovel,spade
show,demonstrate-(to)
show_of_hands
shower-(to)
shower
shower_chair
showjumping_(horse)
shrimp
shuttlecock,birdie_(badminton)
sibling(s)
sick,ill
side_(body)
side_(enclosure)
sidecar_(motorcycle)
sidecar_(motorcycle_sport)
sieve,colander,strainer
sight,vision,visual_sense
sign,advertisement
sign,signal
sign-(to)
sign_(OLD)
sign_language
sign_of_the_cross
signal,broadcast,transmitting
signal_receiver_(1)
signal_receiver_(2)
signal_reception
signal_strength_meter
signature
signature_stamp
silence,quiet
silent
silk
silk_fabric
silver
silversmith
similar,like,alike
similar_looking,looks_similar
similar_sound,sounds_like
simmer,poach-(to)
sin-(to)
sin
sing-(to)
singalong
singer
single_father
single_mother
single_parent
single_parent_family
singular
sink,basin
sinner
siren_of_the_woods
sister-in-law_(husband's_sister)
sister-in-law_(partner's_sister)
sister-in-law_(wife's_sister)
sister
sit-(to)
sit_ski_(OLD)
sitski,sit_ski
sitski,sit_ski_(sport)
sitting_mat
six_(digit),6
six_(index_number)
size
skateboard
skating
skeleton
ski,runner_(sled_etc)
ski_boot(s)
ski_jumping
ski_pole(s)
skiing_(activity)
skiing_(sport)
skin
skin_disease,eczema
skirt
skis_(pair_of)
skull,cranium
skullcap,kipa,yarmulke
skunk
sky
sky_sports
skyscraper
skytrain,monorail
slalom
slang
slaughter-(to)
slaughter
slaughterer
slaughterhouse,abattoir
sled,sledge,sleigh,toboggan
sled_dog
sled_sport
sleep-(to)
sleep
sleep_medication
sleeping_bag
sleeping_pill
sleeping_place,nest_(animals)
sleepless
sleepy
sleeve(s)
slice-(to)
slice
slice_of_bread,bread_slice
sliced
slide,skid,slip-(to)
slide
slip,petticoat,half-slip,underskirt
slipper(s)
sloping,sloped,slanting,slanted
slow,slowly
slow,slowly_(OLD)
small_intestine
small_pancake,blini
smart,bright,clever,intelligent
smartness,brightness,cleverness,intelligence
smartphone,digital_phone
smash,grind,shatter,splinter-(to)
smell,give_off_odour-(to)
smell,odour
smell,sense_of_smell,olfaction
smell-(to)
smell_bad,stink-(to)
smile,grin-(to)
smoke-(to)
smoke
smoking_(cigarette)
smoking_(pipe)
smoking_addiction_(1)
smoking_addiction_(2)
smooth
snack_(food)
snack_(meal)
snail
snake
snake_(dangerous),viper,boa_(etc)
snake_(not_dangerous),grass_snake_(etc)
sneeze-(to)
sniffer_dog
snorkeling,scuba_diving,deep_sea_diving_(sport)
snot
snow-(to)
snow
snowball
snowboard
snowboarding
snowflake
snowman
snowmobile
snowplow,snowplough
snowshoe
snowshoe_(OLD)
snowstorm
snowsuit,winter_clothing
snuff,kat,coca
snuff_(nose)
soap,detergent
social
social_network,facebook_(etc)
social_worker
society
sociologist
sociology
soda_pop,pop,soft_drink
soft
soft_cheese
software,computer_program,application,app
solar_eclipse
solar_energy,solar_power
solar_system
soldier,warrior
sole_(of_shoe)
solid_thing
solve-(to)
some,any
somersault
somersault_(person)
sometimes
son-in-law
son
song
songbird,finch,thrush
soon
soprano
sorry
sort,differentiate,separate,classify-(to)
sort_garbage,separate_waste-(to)
soul
sound-(to)
sound
sound_recorder,tape_recorder
soup,broth
south
southeast
southern
southward
southwest
sow
space,dimension
space_travel,space_voyage,space_flight
spaghetti
spaghetti_(OLD)
spark
sparkling_wine
spasm
speaker,lecturer
special,particular
specific
speech
speech_(event)
speech_impaired
speech_impaired_(OLD)
speech_impairment,dysarthria
speech_recognition
speech_therapist
speech_therapy
speech_therapy_room
speed
speed_cycling
speed_skating
speedometer
spell-(to)
spending_spree
sperm
sperm_destruction
spermicide
spice_box
spider
spider_web,cobweb,orb_web
spill,slop-(to)
spine,backbone
spiral,curl_(shape)
spiral
spirit
spiritual_awareness
spit-(to)
spitting
splash-(to)
spleen
splint_(orthopedic)
splurge-(to)
spoon
sport
sport_(OLD)
sport_(class)
sport_elf
sport_fanatic
sport_lesson
sport_shop
sport_stick
sport_stick_and_ball,bandy_stick
sport_stick_and_puck,hockey_stick
sports_centre
sports_glove,glove,mitt
spot,mark
spouse,cohabitant,partner
spray,vaporization
spray,vaporize-(to)
spray_bottle,vaporizer,spray_can
spread,paste
spread_(cover_with_spread)-(to)
spreadable_cheese
spring
spring_(ckb)
spring_(water)
springbok
sprout,germinate-(to)
sprout
square_(description)
square_(oblique)
square_(public)
square_(shape)
squash,pumpkin
squash_(sport)
squash_(sport)_(OLD)
squirrel
stable
staff
stairs,steps
stallion,entire
stamp
stand-(to)
stand-in,substitute,alternate
stander
stander_(wheeled)
standing_(standing_person)
star
star_of_David
star_of_David_(a)
starboard
starfish
starfish_(OLD)
starfruit,carambola
starvation
state_of_mind
statement
station
stave,staff
stay,remain-(to)
steak
steal-(to)
steam-(to)
steam
steam_bath
steamer
steamship
steel
steep
steering_wheel
stem,stalk
step,stair
stepdaughter
stepfather
stepmother
stepparent,step-parent
stepson
sterilization
stern
stethoscope
stew
stick,log
stickball
sticking_plaster,bandaid
still,calm,peaceful,tranquil
still,continuing,ongoing
still,continuously
stir-(to)
stirrup
stocking(s),sock(s),pantyhose,tights
stolen_goods
stoma,medical_hole
stomach,abdomen,belly
stomach,tummy,tum
stomach_flu
stomach_illness
stone,rock
stone_(material)
stone_age
stop,arrive,end-(to)
stop,platform_(vehicle)
stop,platform_(vehicle)_(OLD)
storage_jar,preserving_jar
store,shop
store_(OLD)
storeroom
storm
story,report,tale
story_(historical),historic_story
stove,furnace,heater,oven
stovetop
strange
stranger,unknown_(person)
stranger
strap,string,velcro,rope,cord
strategy
straw,drinking_straw
strawberry
stream_(digital),data_stream
stream_(digital_data)-(to)
streamed,streaming_(digital_data)
street
street_and_building
strength
stress
stress_(for_time)-(to)
stress_(for_time)
stressed,stressful
stressed_(for_time),pushed_(for_time),in_a_rush
stretch_(elongate)-(to)
stretch_(muscles)-(to)
string
string_(for_musical_instrument)
string_bean,green_bean,runner_bean,wax_bean
striped
stroke-(to)
strong,powerful
structure,construction
student,pupil
study-(to)
stupid,dumb
stupid,dumb_(OLD)
stutter-(to)
stuttering
subject_(of_study)
submerged_rock,reef
substance
subtract,remove,take_away-(to)
subtraction,loss
subway,metro,underground,tube
succeed-(to)
success
suck-(to)
suddenly,abrupt,sudden
suffix
sufganiya
sugar,sweetener
sugar_lump,cube_(sugar)
suggest,propose-(to)
suggestion,proposal
suicide
suit
suit_of_armour
sukkah
sulky
summary,abstract
summer
summer_(ckb)
summer_day
summer_day_camp
summer_house,summerhouse
sun
sun_lounger,deck_chair
sunbathe-(to)
sunburn
sunflower
sunglasses
sunny
sunrise
sunscreen,sunblock,sun_lotion
sunset
suntan
superlative_most
supernatural-(noun)
supernatural
supper,dinner
support-(to)
support_(oral)
support_(orally)-(to)
supporters,cheering_section
surfboard
surgeon
surprise-(to)
surprise-(to)_(OLD)
surprise
surprised
surrounded,encircled,surrounding
sushi
suspender(s)
swallow-(to)
swamp,bog,marsh
swan
sweat,perspiration
sweat,perspire-(to)
sweaty,sweating,perspiring
sweet,confection
sweet_(metaphor)
sweet_(taste)
sweet_drink
sweet_potato,yam
sweet_shop,candy_store
sweetheart,lover
sweetness,sweet
swim-(to)
swim_centre
swimming,swim
swimming_(sport)
swimming_hall,indoor_swimming_pool
swimming_pool
swimming_rule(s)
swimsuit,swimwear,bathing_suit
swing,sway,rock-(to)
swing,swinging
swing
switch-(to)
switch
switch_off,turn_off-(to)
switch_on,turn_on-(to)
swordfish
symbol_display,symbol_board,symbol_chart
synagogue
synchronized_diving,synchro_diving_(sport)
synchronized_swimming_(sport)
syntax
synthesizer,synthesiser,keyboard
synthetic_fabric
synthetic_speech,text-to-speech,tts
syringe
syrup
syrup_(from_tree)
t_(lowercase)
table
table_game
table_mat,placemat
table_sports
table_tennis,ping-pong_(activity)
table_tennis,ping-pong_(activity)_(OLD)
table_tennis,ping-pong_(sport)
table_tennis,ping-pong_(sport)_(OLD)
tablecloth
tablespoon
tablet_computer,tablet,tablet_PC_(1)
tablet_computer,tablet,tablet_PC_(2)
tabletop
tack_room
taco,taco_shell
tadpole
tahini,sesame_seed_spread
tail
tail_(airplane)
tail_(horse)
tail_lift,lift
tail_wing_(airplane)
tailor,dressmaker,seamstress
take,bring,carry,move-(to)
take_away,remove-(to)
take_off_(airplane)-(to)
take_off_(rocket)-(to)
takeoff,take-off,airplane_take-off
takeoff_(rocket)
talcum_powder
tallith
tambourine_(1)
tambourine_(2)
tandem_bicycle
tangerine,clementine,mandarin
tank
tanker
tanker_truck,tank_lorry
tap_(1)
tap_(2)
taste,gustation,sense_of_taste
taste-(to)
taste
tasteless,not_tasty,not_good
tasty,good,appetizing
tattoo,picture_on_skin
tattoo_(permanent)
tattoo_(sticker)
tax
tax_(national,federal)
tax_(real_estate)
tax_(sales)
tax_(state,regional)
taxi,cab
taxi_driver,cab_driver
tea
tea_break,coffee_break
teach,instruct-(to)
teacher,instructor
teacher,pedagogue,educator
teacher,pedagogue,educator_(in_combinations)
team
team_(sport)
teamwork
tear,teardrop
tear_along,advance_fast,go_fast-(to)
tease-(to)
teaspoon
technology
teenager,adolescent,youth
teeth
teetotalism
tefillin
telephone,call
telephone_card
telescope
television
temperature
temporary
temporary_home
ten_o'clock_eating_break
tendon
tennis,racket_sport,racquet_sport
tennis,racquet_sports_(OLD)
tennis_(activity)
tennis_(activity)_(OLD)
tenor
tense
tent
term,semester
termite,wood_destroying_insect
terrified
terror,panic
terrorism
terrorist
terrorize-(to)
test,assessment,exam
testicle
testify-(to)
testimony
text_phone
textile_craft
thank-(to)
thanks,thank_you
thanksgiving
that_(conj)
that_(there)
thaw,melt-(to)
thawing,melting
the
theatre
theft
their,theirs-(feminine_plural)
their,theirs-(indefinite)
their,theirs-(masculine_plural)
their,theirs-(persons)
then,so,later
theologian,theologist
theology,philosophy_of_religion
therapeutic_riding
therapist
therapist_(OLD)
therapy
therapy_centre,rehabilitation_centre
there
therefore,so,so_that
thermometer
thermos,cooler,flask
these
they,them,themselves-(feminine_plural)
they,them,themselves-(indefinite)
they,them,themselves-(masculine_plural)
they,them,themselves-(persons)
thief
thigh,upper_leg
thin,slim,narrow
thing,object
think,reason-(to)
thinness,narrowness
thirsty
this
this_month
this_week
this_year
those
thread,string,cord
three_(digit),3
three_(index_number)
three_Danish_waters_(OLD)
three_quarters
thrilling,scary
throat
through
throw-(to)
thumb
thunder
thyroid_gland
ticket,pass
tidal_wave
tide
tie,bind_together,lash-(to)
tie,necktie
tie_whipping_knot-(to)
tiger
tile
time
timer
tin,can
tin
tiptoe-(to)
tire,tyre
tired,exhausted,weary_(OLD)
tired,weary
tissue
tissue_(body)
to,toward,towards
toast-(to)
toast
toaster
tobacco
toboggan
today
toe
together,attached,appended,fastened,joined
toilet
toilet_chair,commode_chair
toilet_paper
tomato
tomato_sauce
tomb
tombstone
tomorrow
tomorrow_night
tongue
tonight
tonsils
too_bad,I'm_sorry,I'm_so_sorry
too_much,too_many
tool,instrument
tooth
tooth_fairy
toothbrush
toothpaste
toothpick
top,top_of_a_thing
top
tornado
touch,feel-(to)
touch,sense_of_touch,tactile_sense
touch,touching
touch_screen
touchpad,trackpad
tour,sightseeing
tourist
tourist_(foreign)
towboat,tugboat
towel
towel_(OLD)
tower
town,city_(small)
toy
toy_(in_combinations)
toy_animal,stuffed_animal
toy_shop
trachea,wind_pipe
tracheotomy_tube,tracheal_tube
track
trackball
tracker
tractor
traffic
traffic_light
traffic_rule(s)
tragedy
trailer,container_transport
train
train_station_(building)
train_station_(platforms)
tram
trampoline
transgender
transgender_person
translate-(to)
translation
transport,transportation
transvestite_(female)
transvestite_(male)
trap-(to)
trap
trapeze
travel-(to)
traveller
tray
treat,care_for_(medically)-(to)
treat
treatment
tree
tree_or_wood_destruction
tremor,shudder
trial
triangle
triangle_(instrument)_(1)
triangle_(instrument)_(2)
triangular
triathlon
tricycle
trip,journey,travel,voyage
troll
troll_(tailed)
trolleybus
trombone
tropical_rain_forest,jungle
trot_(horse)-(to)
trouble
troublesome
truck,lorry
true,truly,truthful,truthfully
trumpet,horn,cornet_(1)
trumpet,horn,cornet_(2)
trunk,tree_trunk,bole
trust,confidence
trust-(to)
truth
try,attempt-(to)
tsunami
tuba_(1)
tuba_(2)
tubal_ligation
tuft_of_grass,tussock
tumble-drier,tumble-dryer
tuna_fish
tune,melody
tuning_fork
tunnel,subway,underpass
turkey_(bird)
turkey_(food)
turn,play
turn,turning
turn-(to)
turnip,rutabaga,vegetable_(large-leafed)
turquoise
turtle,tortoise
twin_brother
twin_sister
twinkle,shine,sparkle-(to)
twins
two_(digit),2
two_(index_number)
two_storey_building
two_thirds
type,kind,sort,category
type-(to)
u_(lowercase)
ugh,yuk-(exclamatory)
ugly,unattractive
ukulele
umami
umami_tasting
umbilical_cord
umbrella
uncertain,unsure
uncle
uncomfortable
unconscious,comatose
unconsciousness,coma,comatoseness
under,below,inferior
under_(ground_level)
underground,below_ground
underground_station,subway_station
underpants,briefs,panties
undershirt
understand,see-(to)
understanding,comprehension
underwear,underclothes
undo-(to)
undo_(computer)-(to)
unemployed
unemployment
unending,endless
unfair,unjust
unfinished
unfold-(to)
unfold-(to)_(OLD)
unfolding
unforgivable,inexcusable
unharness_(horse)-(to)
unicorn
unicycle,monocycle,one-wheeled_vehicle
unicycle,ride_a_one-wheeled_vehicle-(to)
unidentified_object_(suspected_explosive)
uniform
uninhabited
union_(political_unit)
unit,example,sample,for_example,e.g.
universal,world-wide
university
unless
until,till,to
untrue,false
untruth,falsity,falsehood
up,upward
up_and_down
up_and_down_(OLD)
upload-(to)
upload
upper_arm
upper_body
upset,disturbance,agitation
upset
upward_and_backward
upward_and_forward
urethra
urinate,make_water,pass_water,micturate,pee,piddle,piss,wee-(to)
urine,piss,pee,piddle,weewee,water
urine_bottle
urn
usage,use
use-(to)
usually,usual
usually_do,habitually_do-(to)
utensil
uterine_contraction
uterus,womb
v_(lowercase)
vacation,holiday
vacuum_cleaner
vagina
vaginal_discharge
valley
vampire
van,minibus
vanilla
vanilla_(liquid)
vanilla_(powder)
vanilla_sauce
vas_deferens
vascular_system
vase,urn,trophy_cup
vasectomy
veal
vegan_food
vegetable(s)
vegetable_(above_ground)
vegetable_(below_ground)
vegetable_(oval-shaped)
vegetarian_(food)
vegetarian_(person)
vehicle,carriage,railway_car
vehicle_(long)
veil
venereal_disease
venereal_papilloma
verb
vertebrate
vertical-(a)
vertical
very_much,very_many
vestment
veterinarian
video_phone
video_recorder
view_of_life
village
vinegar
viola
violin
viral_infection
virginity
virus
virus_(computer)
visa
visible,sighted
vision,apparition
visit-(to)
visit
visitor,guest
visual_impairment
visually_impaired
visually_impaired_(OLD)
voice
volcano
volleyball
voltage
volte_(horse)-(to)
voltmeter
voluntary
voluntary_work,unpaid_work
volunteer
volunteering
vomit,throw_up,puke-(to)
vomiting,vomit,puking
voter,elector
voyeurism
vulture
vulva
w_(lowercase)
wading_pool,paddling_pool
waffle
wage(s),pay,salary
wagon,cart,truck
waist
wait,waiting
wait-(to)
waiter,waitress
wake_up-(to)
wakefulness,alertness
walk,go-(to)
walk,walking
walk_(horse)-(to)
walker,walking_aid_(1)
walker,walking_aid_(2)
walkway,footpath
wall
wall_climbing
walrus
wand
want,desire-(to)
want,desire
war
warm
warn-(to)
warning
wart,papilloma_(venereal)
wash,bathe,bath-(to)
wash_up,do_the_dishes-(to)
washable
washcloth,washrag,flannel
washer
washing_machine,washer
wasp
waste,garbage,rubbish,trash
waste_sorting,garbage_sorting,source_separation_(of_waste)
watch,wristwatch
watch-(to)
watch_tower,observation_tower
watchdog
watchful,alert
water,fluid,liquid
water-(to)
water_animal_(big_tail)
water_bucket
water_creature
water_flower,water_lily
water_ice_lollipop
water_meter
water_on_ground_(flooding)
water_play
water_polo
water_ski
water_skiing
water_snake
water_sports
water_tower
water_toy
waterfall
wave
wave_length
wave_power,wave_energy
way
we,us,ourselves-(feminine)
we,us,ourselves-(masculine)
we,us,ourselves
weak
weakness_(weak_person)
weapon
weather
weather_forecast
weather_satellite,spy_satellite
weave-(to)
website,domain_name,homepage,internet_domain
week
weekend
weekend_(6-7)
weekend_(7-1)
weigh-(to)
weight
weight_(a)
weight_(measurement)
weight_lifting
welcome
well,water_well
werewolf
west
western
westward
wet,damp,moist,watery
whale
what,question_mark_(small)
what
what_(thing)-(question)
what_kind-(question)
wheat
wheel
wheelchair
wheelchair_bike
wheelchair_straps
wheelchair_tricycle
when,what_time-(question)
when
where-(question)
where
which,that-(relative)
which-(question)
whipping_knot
whisk,beat-(to)
whisk,beater
whisper-(to)
whistle-(to)
white
who,that,which-(relative)
who,whom,that-(relative)
who,whom-(question)
whose-(question)
whose_(neutral)
whose_(person)
why-(question)
wicket
wide,broad
wideness,broadness
wife
wiggle,squirm-(to)
wiggly
wild_strawberry
wilderness
wildflower
win-(to)
wind
wind_instrument
wind_power,wind_energy,wind_farm
wind_surfing
wind_turbine
windmill
window
wine
wing(s)
wink,blink-(to)
winter_(ckb)
winter_(rain)
winter_(snow)
winter_day
winter_house
winter_sports
wipe,dust,polish-(to)
wire,cable
wire,cable_(OLD)
wireless_connection,WIFI_(OLD)
wireless_connection
wish,desire-(to)
wish,desire
witch
with
witness
wizard
wok,wok_pan
woking
wolf,dingo,wild_dog
woman,female
woman_(below_waist)
woman_doll_(e.g._Barbie)
wonder,inquire,enquire,be_curious-(to)
wood,lumber,timber
woodcraft
woodpecker
woodwind_instrument
wool
word
work,employment,job
work-(to)
work_day
work_from_home-(to)
work_method
work_of_art,art_object
workbook
worker
working_from_home
workplace
worksheet
world
worm
worn-out,raddled
worry-(to)
worry
wound,cut,sore
wow,super,great,neat,cool-(exclamatory)
wrap,wind-(to)
wrapping,paper_roll
wrapping
wreck,wreckage_(airplane)
wreck,wreckage_(boat)
wrestling_(activity)
wrestling_(sport)
wrist
wrist_splint
write-(to)
writer,author
writing_(class)
writing_difficulty
x_(lowercase)
xylophone,vibraphone_(1)
xylophone,vibraphone_(2)
y_(lowercase)
yard
yarn
yawn-(to)
year
yeast
yell,scream-(to)
yellow_(bci)
yellow_(ckb)
yen
yes-(exclamatory)
yesterday
yogurt,yoghurt
yogurt,yoghurt_(frozen)
you,yourself-(feminine_singular)
you,yourself-(masculine_singular)
you,yourself
you,yourselves-(feminine_plural)
you,yourselves-(masculine_plural)
you,yourselves-(plural)
you_are_welcome,you're_welcome
young
young_animal
your,yours-(feminine_plural)
your,yours-(feminine_singular)
your,yours-(masculine_plural)
your,yours-(masculine_singular)
your,yours-(plural)
your,yours-(singular)
z_(lowercase)
zebra
zero_(digit),0
zero_(index_number)
zigzag
zigzag_line
zombie
zoo
zoologist
zoology`
